#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: generate_dashboard_link
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: generate_dashboard_link
short_description: Generate a direct URL/link/weburl for a LogicMonitor (LM) dashboard. 

**Returns:** Complete dashboard URL with full group hierarchy path, dashboard details (id, name, groupName), and group path array. URL pattern: https://test.logicmonitor.com/santaba/uiv4/dashboards/dashboardGroups-{path},dashboards-{id}

**When to use:** 
- Share dashboard links in Slack/email/tickets
- Create documentation with direct dashboard links
- Embed dashboard URLs in runbooks
- Build custom reports with clickable links

**Why use this:** Provides the complete navigable URL including all parent group IDs, so the link opens the dashboard in correct context within the UI navigation tree. 

**Workflow:** First use "list\_dashboards" to find dashboard ID, then use this tool to generate the shareable link. 

**Related tools:** "list\_dashboards" (find dashboard), "get\_dashboard" (get details).
description:
  - Generate a direct URL/link/weburl for a LogicMonitor (LM) dashboard. 

**Returns:** Complete dashboard URL with full group hierarchy path, dashboard details (id, name, groupName), and group path array. URL pattern: https://test.logicmonitor.com/santaba/uiv4/dashboards/dashboardGroups-{path},dashboards-{id}

**When to use:** 
- Share dashboard links in Slack/email/tickets
- Create documentation with direct dashboard links
- Embed dashboard URLs in runbooks
- Build custom reports with clickable links

**Why use this:** Provides the complete navigable URL including all parent group IDs, so the link opens the dashboard in correct context within the UI navigation tree. 

**Workflow:** First use "list\_dashboards" to find dashboard ID, then use this tool to generate the shareable link. 

**Related tools:** "list\_dashboards" (find dashboard), "get\_dashboard" (get details).
  - This module wraps the MCP tool 'generate_dashboard_link'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  dashboardId:
    description:
      - The ID of the dashboard to generate a link for
    type: float
    required: true
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Generate a direct URL/link/weburl for a LogicMonitor (LM) dashboard. 

**Returns:** Complete dashboard URL with full group hierarchy path, dashboard details (id, name, groupName), and group path array. URL pattern: https://test.logicmonitor.com/santaba/uiv4/dashboards/dashboardGroups-{path},dashboards-{id}

**When to use:** 
- Share dashboard links in Slack/email/tickets
- Create documentation with direct dashboard links
- Embed dashboard URLs in runbooks
- Build custom reports with clickable links

**Why use this:** Provides the complete navigable URL including all parent group IDs, so the link opens the dashboard in correct context within the UI navigation tree. 

**Workflow:** First use "list\_dashboards" to find dashboard ID, then use this tool to generate the shareable link. 

**Related tools:** "list\_dashboards" (find dashboard), "get\_dashboard" (get details).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Generate a direct URL/link/weburl for a LogicMonitor (LM) dashboard. 

**Returns:** Complete dashboard URL with full group hierarchy path, dashboard details (id, name, groupName), and group path array. URL pattern: https://test.logicmonitor.com/santaba/uiv4/dashboards/dashboardGroups-{path},dashboards-{id}

**When to use:** 
- Share dashboard links in Slack/email/tickets
- Create documentation with direct dashboard links
- Embed dashboard URLs in runbooks
- Build custom reports with clickable links

**Why use this:** Provides the complete navigable URL including all parent group IDs, so the link opens the dashboard in correct context within the UI navigation tree. 

**Workflow:** First use "list\_dashboards" to find dashboard ID, then use this tool to generate the shareable link. 

**Related tools:** "list\_dashboards" (find dashboard), "get\_dashboard" (get details).
      leogallego.logicmonitor_mcp.generate_dashboard_link:
        dashboardId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "generate_dashboard_link"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            dashboardId=dict(
                type="float",
                required=True,
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
