#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: generate_alert_link
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: generate_alert_link
short_description: Generate a direct URL/link/weburl for a LogicMonitor (LM) alert. 

**Returns:** Direct URL to alert details page. URL pattern: https://test.logicmonitor.com/santaba/uiv4/alerts/{alertId}

**When to use:** 
- Include alert links in Slack/PagerDuty notifications
- Share alert context with team members
- Create incident tickets with direct alert references
- Build alert reports with clickable links

**Why use this:** Simplifies alert investigation by providing direct navigation to the alert details page with full context, history, and acknowledgement options. 

**Workflow:** Get alertId from "list\_alerts", then use this tool to generate the shareable link for team collaboration. 

**Related tools:** "list\_alerts" (find alerts), "get\_alert" (get details), "acknowledge\_alert" (acknowledge).
description:
  - Generate a direct URL/link/weburl for a LogicMonitor (LM) alert. 

**Returns:** Direct URL to alert details page. URL pattern: https://test.logicmonitor.com/santaba/uiv4/alerts/{alertId}

**When to use:** 
- Include alert links in Slack/PagerDuty notifications
- Share alert context with team members
- Create incident tickets with direct alert references
- Build alert reports with clickable links

**Why use this:** Simplifies alert investigation by providing direct navigation to the alert details page with full context, history, and acknowledgement options. 

**Workflow:** Get alertId from "list\_alerts", then use this tool to generate the shareable link for team collaboration. 

**Related tools:** "list\_alerts" (find alerts), "get\_alert" (get details), "acknowledge\_alert" (acknowledge).
  - This module wraps the MCP tool 'generate_alert_link'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  alertId:
    description:
      - The ID of the alert to generate a link for
    type: str
    required: true
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Generate a direct URL/link/weburl for a LogicMonitor (LM) alert. 

**Returns:** Direct URL to alert details page. URL pattern: https://test.logicmonitor.com/santaba/uiv4/alerts/{alertId}

**When to use:** 
- Include alert links in Slack/PagerDuty notifications
- Share alert context with team members
- Create incident tickets with direct alert references
- Build alert reports with clickable links

**Why use this:** Simplifies alert investigation by providing direct navigation to the alert details page with full context, history, and acknowledgement options. 

**Workflow:** Get alertId from "list\_alerts", then use this tool to generate the shareable link for team collaboration. 

**Related tools:** "list\_alerts" (find alerts), "get\_alert" (get details), "acknowledge\_alert" (acknowledge).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Generate a direct URL/link/weburl for a LogicMonitor (LM) alert. 

**Returns:** Direct URL to alert details page. URL pattern: https://test.logicmonitor.com/santaba/uiv4/alerts/{alertId}

**When to use:** 
- Include alert links in Slack/PagerDuty notifications
- Share alert context with team members
- Create incident tickets with direct alert references
- Build alert reports with clickable links

**Why use this:** Simplifies alert investigation by providing direct navigation to the alert details page with full context, history, and acknowledgement options. 

**Workflow:** Get alertId from "list\_alerts", then use this tool to generate the shareable link for team collaboration. 

**Related tools:** "list\_alerts" (find alerts), "get\_alert" (get details), "acknowledge\_alert" (acknowledge).
      leogallego.logicmonitor_mcp.generate_alert_link:
        alertId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "generate_alert_link"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            alertId=dict(
                type="str",
                required=True,
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
