#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: generate_website_link
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: generate_website_link
short_description: Generate a direct direct URL/link/weburl for a LogicMonitor (LM) website monitor with full hierarchy path for easy sharing and navigation. 

**What this does:** Creates shareable URL that opens specific website monitor in LogicMonitor UI, preserving the full folder hierarchy path. Link works for anyone with access to the LogicMonitor portal. 

**Returns:** Complete URL in format: https://test.logicmonitor.com/santaba/uiv4/websites/treeNodes#websiteGroups-{groupId1},websiteGroups-{groupId2},...,websites-{websiteId} 

**When to use:** 
- Share website monitor with team (Slack/email/tickets)
- Create documentation with direct links
- Build custom dashboards/reports with LM links
- Reference in incident tickets
- Bookmark frequently accessed monitors

**Required parameters:** 
- websiteId: Website monitor ID (from "list\_websites" or "search\_websites")

**Common use cases:** 

**Share in Slack/Teams:** "Production API health check is failing: [View Monitor](generated-url-here)" 

**Incident ticket documentation:** "INC-12345: Website monitor showing SSL certificate expiring in 7 days. See: {generated-url}" 

**Runbook links:** "If homepage monitoring alerts, check: {generated-url-for-homepage-monitor}" 

**Custom reporting:** Build report that includes clickable links to each website monitor for quick access. 

**Link structure explained:** The URL includes complete folder path (websiteGroups) so when clicked, the UI shows: 
- Full breadcrumb navigation (e.g., "All Website Monitors > Production > External APIs > Homepage Check")
- Website monitor details page
- Recent check history and availability
- Current status and response times

**Why use generated links:** 
- **Shareable:** Send exact monitor to teammates
- **Bookmarkable:** Save frequent monitors for quick access
- **Integration-friendly:** Use in external tools, tickets, wikis
- **Context-preserving:** Shows full folder hierarchy when opened

**Workflow example:** 
- Find website monitor: list_websites() → websiteId: 789
- Generate link: generate_website_link(websiteId: 789)
- Share link: "Check this monitor: https://company.logicmonitor.com/santaba/uiv4/websites/..."

**Access requirements:** Link recipients must: 
- Have LogicMonitor user account
- Have permissions to view website monitors
- Have access to specific website monitor (based on access groups)

**Best practices:** 
- Use in incident documentation for traceability
- Include in runbooks for quick troubleshooting access
- Add to monitoring dashboards for drill-down capability
- Share with stakeholders who have LM access

**Related tools:** "list\_websites" (find website), "get\_website" (verify details), "generate\_dashboard\_link" (for dashboards), "generate\_resource\_link" (for resources/devices), "generate\_alert\_link" (for alerts).
description:
  - Generate a direct direct URL/link/weburl for a LogicMonitor (LM) website monitor with full hierarchy path for easy sharing and navigation. 

**What this does:** Creates shareable URL that opens specific website monitor in LogicMonitor UI, preserving the full folder hierarchy path. Link works for anyone with access to the LogicMonitor portal. 

**Returns:** Complete URL in format: https://test.logicmonitor.com/santaba/uiv4/websites/treeNodes#websiteGroups-{groupId1},websiteGroups-{groupId2},...,websites-{websiteId} 

**When to use:** 
- Share website monitor with team (Slack/email/tickets)
- Create documentation with direct links
- Build custom dashboards/reports with LM links
- Reference in incident tickets
- Bookmark frequently accessed monitors

**Required parameters:** 
- websiteId: Website monitor ID (from "list\_websites" or "search\_websites")

**Common use cases:** 

**Share in Slack/Teams:** "Production API health check is failing: [View Monitor](generated-url-here)" 

**Incident ticket documentation:** "INC-12345: Website monitor showing SSL certificate expiring in 7 days. See: {generated-url}" 

**Runbook links:** "If homepage monitoring alerts, check: {generated-url-for-homepage-monitor}" 

**Custom reporting:** Build report that includes clickable links to each website monitor for quick access. 

**Link structure explained:** The URL includes complete folder path (websiteGroups) so when clicked, the UI shows: 
- Full breadcrumb navigation (e.g., "All Website Monitors > Production > External APIs > Homepage Check")
- Website monitor details page
- Recent check history and availability
- Current status and response times

**Why use generated links:** 
- **Shareable:** Send exact monitor to teammates
- **Bookmarkable:** Save frequent monitors for quick access
- **Integration-friendly:** Use in external tools, tickets, wikis
- **Context-preserving:** Shows full folder hierarchy when opened

**Workflow example:** 
- Find website monitor: list_websites() → websiteId: 789
- Generate link: generate_website_link(websiteId: 789)
- Share link: "Check this monitor: https://company.logicmonitor.com/santaba/uiv4/websites/..."

**Access requirements:** Link recipients must: 
- Have LogicMonitor user account
- Have permissions to view website monitors
- Have access to specific website monitor (based on access groups)

**Best practices:** 
- Use in incident documentation for traceability
- Include in runbooks for quick troubleshooting access
- Add to monitoring dashboards for drill-down capability
- Share with stakeholders who have LM access

**Related tools:** "list\_websites" (find website), "get\_website" (verify details), "generate\_dashboard\_link" (for dashboards), "generate\_resource\_link" (for resources/devices), "generate\_alert\_link" (for alerts).
  - This module wraps the MCP tool 'generate_website_link'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  websiteId:
    description:
      - The ID of the website monitor to generate a link for
    type: float
    required: true
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Generate a direct direct URL/link/weburl for a LogicMonitor (LM) website monitor with full hierarchy path for easy sharing and navigation. 

**What this does:** Creates shareable URL that opens specific website monitor in LogicMonitor UI, preserving the full folder hierarchy path. Link works for anyone with access to the LogicMonitor portal. 

**Returns:** Complete URL in format: https://test.logicmonitor.com/santaba/uiv4/websites/treeNodes#websiteGroups-{groupId1},websiteGroups-{groupId2},...,websites-{websiteId} 

**When to use:** 
- Share website monitor with team (Slack/email/tickets)
- Create documentation with direct links
- Build custom dashboards/reports with LM links
- Reference in incident tickets
- Bookmark frequently accessed monitors

**Required parameters:** 
- websiteId: Website monitor ID (from "list\_websites" or "search\_websites")

**Common use cases:** 

**Share in Slack/Teams:** "Production API health check is failing: [View Monitor](generated-url-here)" 

**Incident ticket documentation:** "INC-12345: Website monitor showing SSL certificate expiring in 7 days. See: {generated-url}" 

**Runbook links:** "If homepage monitoring alerts, check: {generated-url-for-homepage-monitor}" 

**Custom reporting:** Build report that includes clickable links to each website monitor for quick access. 

**Link structure explained:** The URL includes complete folder path (websiteGroups) so when clicked, the UI shows: 
- Full breadcrumb navigation (e.g., "All Website Monitors > Production > External APIs > Homepage Check")
- Website monitor details page
- Recent check history and availability
- Current status and response times

**Why use generated links:** 
- **Shareable:** Send exact monitor to teammates
- **Bookmarkable:** Save frequent monitors for quick access
- **Integration-friendly:** Use in external tools, tickets, wikis
- **Context-preserving:** Shows full folder hierarchy when opened

**Workflow example:** 
- Find website monitor: list_websites() → websiteId: 789
- Generate link: generate_website_link(websiteId: 789)
- Share link: "Check this monitor: https://company.logicmonitor.com/santaba/uiv4/websites/..."

**Access requirements:** Link recipients must: 
- Have LogicMonitor user account
- Have permissions to view website monitors
- Have access to specific website monitor (based on access groups)

**Best practices:** 
- Use in incident documentation for traceability
- Include in runbooks for quick troubleshooting access
- Add to monitoring dashboards for drill-down capability
- Share with stakeholders who have LM access

**Related tools:** "list\_websites" (find website), "get\_website" (verify details), "generate\_dashboard\_link" (for dashboards), "generate\_resource\_link" (for resources/devices), "generate\_alert\_link" (for alerts).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Generate a direct direct URL/link/weburl for a LogicMonitor (LM) website monitor with full hierarchy path for easy sharing and navigation. 

**What this does:** Creates shareable URL that opens specific website monitor in LogicMonitor UI, preserving the full folder hierarchy path. Link works for anyone with access to the LogicMonitor portal. 

**Returns:** Complete URL in format: https://test.logicmonitor.com/santaba/uiv4/websites/treeNodes#websiteGroups-{groupId1},websiteGroups-{groupId2},...,websites-{websiteId} 

**When to use:** 
- Share website monitor with team (Slack/email/tickets)
- Create documentation with direct links
- Build custom dashboards/reports with LM links
- Reference in incident tickets
- Bookmark frequently accessed monitors

**Required parameters:** 
- websiteId: Website monitor ID (from "list\_websites" or "search\_websites")

**Common use cases:** 

**Share in Slack/Teams:** "Production API health check is failing: [View Monitor](generated-url-here)" 

**Incident ticket documentation:** "INC-12345: Website monitor showing SSL certificate expiring in 7 days. See: {generated-url}" 

**Runbook links:** "If homepage monitoring alerts, check: {generated-url-for-homepage-monitor}" 

**Custom reporting:** Build report that includes clickable links to each website monitor for quick access. 

**Link structure explained:** The URL includes complete folder path (websiteGroups) so when clicked, the UI shows: 
- Full breadcrumb navigation (e.g., "All Website Monitors > Production > External APIs > Homepage Check")
- Website monitor details page
- Recent check history and availability
- Current status and response times

**Why use generated links:** 
- **Shareable:** Send exact monitor to teammates
- **Bookmarkable:** Save frequent monitors for quick access
- **Integration-friendly:** Use in external tools, tickets, wikis
- **Context-preserving:** Shows full folder hierarchy when opened

**Workflow example:** 
- Find website monitor: list_websites() → websiteId: 789
- Generate link: generate_website_link(websiteId: 789)
- Share link: "Check this monitor: https://company.logicmonitor.com/santaba/uiv4/websites/..."

**Access requirements:** Link recipients must: 
- Have LogicMonitor user account
- Have permissions to view website monitors
- Have access to specific website monitor (based on access groups)

**Best practices:** 
- Use in incident documentation for traceability
- Include in runbooks for quick troubleshooting access
- Add to monitoring dashboards for drill-down capability
- Share with stakeholders who have LM access

**Related tools:** "list\_websites" (find website), "get\_website" (verify details), "generate\_dashboard\_link" (for dashboards), "generate\_resource\_link" (for resources/devices), "generate\_alert\_link" (for alerts).
      leogallego.logicmonitor_mcp.generate_website_link:
        websiteId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "generate_website_link"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            websiteId=dict(
                type="float",
                required=True,
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
