#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_access_group
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_access_group
short_description: Get detailed information about a specific access group in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete access group details: name, description, tenant ID, list of associated resources (which resources/devices/groups are in this access group), list of users assigned to this access group. 

**When to use:** 
- Review which resources are in this access group
- Check which users have access to this group
- Audit access control before modifications
- Verify tenant isolation configuration

**Key information returned:** 
- **Resources:** Which resource/device groups and resources users in this access group can see
- **Users:** Which users are assigned to this access group
- **Tenant ID:** Multi-tenant identifier (MSP environments)

**Impact analysis:** Before modifying access group: 
- Removing resource: Users lose visibility to those resource/device
- Removing user: User loses visibility to all resources in group
- Deleting group: All users lose their access scope

**Workflow:** Use "list\_access\_groups" to find accessGroupId, then use this tool to review complete configuration before modifications. 

**Related tools:** "list\_access\_groups" (find groups), "update\_access\_group" (modify), "list\_users" (see user access).
description:
  - Get detailed information about a specific access group in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete access group details: name, description, tenant ID, list of associated resources (which resources/devices/groups are in this access group), list of users assigned to this access group. 

**When to use:** 
- Review which resources are in this access group
- Check which users have access to this group
- Audit access control before modifications
- Verify tenant isolation configuration

**Key information returned:** 
- **Resources:** Which resource/device groups and resources users in this access group can see
- **Users:** Which users are assigned to this access group
- **Tenant ID:** Multi-tenant identifier (MSP environments)

**Impact analysis:** Before modifying access group: 
- Removing resource: Users lose visibility to those resource/device
- Removing user: User loses visibility to all resources in group
- Deleting group: All users lose their access scope

**Workflow:** Use "list\_access\_groups" to find accessGroupId, then use this tool to review complete configuration before modifications. 

**Related tools:** "list\_access\_groups" (find groups), "update\_access\_group" (modify), "list\_users" (see user access).
  - This module wraps the MCP tool 'get_access_group'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  accessGroupId:
    description:
      - The ID of the access group to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific access group in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete access group details: name, description, tenant ID, list of associated resources (which resources/devices/groups are in this access group), list of users assigned to this access group. 

**When to use:** 
- Review which resources are in this access group
- Check which users have access to this group
- Audit access control before modifications
- Verify tenant isolation configuration

**Key information returned:** 
- **Resources:** Which resource/device groups and resources users in this access group can see
- **Users:** Which users are assigned to this access group
- **Tenant ID:** Multi-tenant identifier (MSP environments)

**Impact analysis:** Before modifying access group: 
- Removing resource: Users lose visibility to those resource/device
- Removing user: User loses visibility to all resources in group
- Deleting group: All users lose their access scope

**Workflow:** Use "list\_access\_groups" to find accessGroupId, then use this tool to review complete configuration before modifications. 

**Related tools:** "list\_access\_groups" (find groups), "update\_access\_group" (modify), "list\_users" (see user access).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific access group in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete access group details: name, description, tenant ID, list of associated resources (which resources/devices/groups are in this access group), list of users assigned to this access group. 

**When to use:** 
- Review which resources are in this access group
- Check which users have access to this group
- Audit access control before modifications
- Verify tenant isolation configuration

**Key information returned:** 
- **Resources:** Which resource/device groups and resources users in this access group can see
- **Users:** Which users are assigned to this access group
- **Tenant ID:** Multi-tenant identifier (MSP environments)

**Impact analysis:** Before modifying access group: 
- Removing resource: Users lose visibility to those resource/device
- Removing user: User loses visibility to all resources in group
- Deleting group: All users lose their access scope

**Workflow:** Use "list\_access\_groups" to find accessGroupId, then use this tool to review complete configuration before modifications. 

**Related tools:** "list\_access\_groups" (find groups), "update\_access\_group" (modify), "list\_users" (see user access).
      leogallego.logicmonitor_mcp.get_access_group:
        accessGroupId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_access_group"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            accessGroupId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
