#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_service
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_service
short_description: Get detailed information about a specific service by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete service details: name, description, health status, dependency tree (all resources comprising service), SLA/SLO configuration, availability statistics, alert rules, service group. 

**When to use:**
- Review service dependencies (what resources are included)
- Check current health status and root cause
- Verify SLA/SLO configuration
- Troubleshoot service downtime
- Understand service architecture


**Key information returned:** 
- **Dependency tree:** All resources/devices/resources that comprise this service 
- **Health calculation:** How service status is determined (e.g., "If ANY web server is down, service is degraded") 
- **Current status:** Operational / Degraded / Down 
- **SLA metrics:** Uptime percentage, outage history 
- **Alert configuration:** When to alert on service issues 

**Troubleshooting workflow:** Service shows "Down" → Check dependency tree → Identify which specific resource(s) failed → Address those resources → Service auto-recovers when dependencies healthy 

**Workflow:** Use "list\_services" to find serviceId, then use this tool for complete dependency analysis. 

**Related tools:** "list\_services" (find service), "update\_service" (modify dependencies), "list\_resources" (see health of dependent resources).
description:
  - Get detailed information about a specific service by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete service details: name, description, health status, dependency tree (all resources comprising service), SLA/SLO configuration, availability statistics, alert rules, service group. 

**When to use:**
- Review service dependencies (what resources are included)
- Check current health status and root cause
- Verify SLA/SLO configuration
- Troubleshoot service downtime
- Understand service architecture


**Key information returned:** 
- **Dependency tree:** All resources/devices/resources that comprise this service 
- **Health calculation:** How service status is determined (e.g., "If ANY web server is down, service is degraded") 
- **Current status:** Operational / Degraded / Down 
- **SLA metrics:** Uptime percentage, outage history 
- **Alert configuration:** When to alert on service issues 

**Troubleshooting workflow:** Service shows "Down" → Check dependency tree → Identify which specific resource(s) failed → Address those resources → Service auto-recovers when dependencies healthy 

**Workflow:** Use "list\_services" to find serviceId, then use this tool for complete dependency analysis. 

**Related tools:** "list\_services" (find service), "update\_service" (modify dependencies), "list\_resources" (see health of dependent resources).
  - This module wraps the MCP tool 'get_service'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  serviceId:
    description:
      - The ID of the service to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific service by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete service details: name, description, health status, dependency tree (all resources comprising service), SLA/SLO configuration, availability statistics, alert rules, service group. 

**When to use:**
- Review service dependencies (what resources are included)
- Check current health status and root cause
- Verify SLA/SLO configuration
- Troubleshoot service downtime
- Understand service architecture


**Key information returned:** 
- **Dependency tree:** All resources/devices/resources that comprise this service 
- **Health calculation:** How service status is determined (e.g., "If ANY web server is down, service is degraded") 
- **Current status:** Operational / Degraded / Down 
- **SLA metrics:** Uptime percentage, outage history 
- **Alert configuration:** When to alert on service issues 

**Troubleshooting workflow:** Service shows "Down" → Check dependency tree → Identify which specific resource(s) failed → Address those resources → Service auto-recovers when dependencies healthy 

**Workflow:** Use "list\_services" to find serviceId, then use this tool for complete dependency analysis. 

**Related tools:** "list\_services" (find service), "update\_service" (modify dependencies), "list\_resources" (see health of dependent resources).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific service by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete service details: name, description, health status, dependency tree (all resources comprising service), SLA/SLO configuration, availability statistics, alert rules, service group. 

**When to use:**
- Review service dependencies (what resources are included)
- Check current health status and root cause
- Verify SLA/SLO configuration
- Troubleshoot service downtime
- Understand service architecture


**Key information returned:** 
- **Dependency tree:** All resources/devices/resources that comprise this service 
- **Health calculation:** How service status is determined (e.g., "If ANY web server is down, service is degraded") 
- **Current status:** Operational / Degraded / Down 
- **SLA metrics:** Uptime percentage, outage history 
- **Alert configuration:** When to alert on service issues 

**Troubleshooting workflow:** Service shows "Down" → Check dependency tree → Identify which specific resource(s) failed → Address those resources → Service auto-recovers when dependencies healthy 

**Workflow:** Use "list\_services" to find serviceId, then use this tool for complete dependency analysis. 

**Related tools:** "list\_services" (find service), "update\_service" (modify dependencies), "list\_resources" (see health of dependent resources).
      leogallego.logicmonitor_mcp.get_service:
        serviceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_service"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            serviceId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
