#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_alert
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_alert
short_description: Get detailed information about a specific alert in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete alert details: alert message, severity, threshold crossed, current value, alert history, escalation chain triggered, acknowledgement details, resource details, datasource/datapoint info, alert rule applied. 

**When to use:** 
- Investigate specific alert after getting ID from "list\_alerts"
- Check threshold and current values
- Review alert history and escalation
- Get context before acknowledging

**Workflow:** First use "list\_alerts" to find the alertId, then use this tool for complete investigation details. 

**Related tools:** "acknowledge\_alert" (acknowledge alert), "add\_alert\_note" (document findings), "generate\_alert\_link" (share with team).
description:
  - Get detailed information about a specific alert in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete alert details: alert message, severity, threshold crossed, current value, alert history, escalation chain triggered, acknowledgement details, resource details, datasource/datapoint info, alert rule applied. 

**When to use:** 
- Investigate specific alert after getting ID from "list\_alerts"
- Check threshold and current values
- Review alert history and escalation
- Get context before acknowledging

**Workflow:** First use "list\_alerts" to find the alertId, then use this tool for complete investigation details. 

**Related tools:** "acknowledge\_alert" (acknowledge alert), "add\_alert\_note" (document findings), "generate\_alert\_link" (share with team).
  - This module wraps the MCP tool 'get_alert'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  alertId:
    description:
      - The ID of the alert to retrieve
    type: str
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  needMessage:
    description:
      - Whether to include alert message details
    type: bool
    required: false
    default: true
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific alert in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete alert details: alert message, severity, threshold crossed, current value, alert history, escalation chain triggered, acknowledgement details, resource details, datasource/datapoint info, alert rule applied. 

**When to use:** 
- Investigate specific alert after getting ID from "list\_alerts"
- Check threshold and current values
- Review alert history and escalation
- Get context before acknowledging

**Workflow:** First use "list\_alerts" to find the alertId, then use this tool for complete investigation details. 

**Related tools:** "acknowledge\_alert" (acknowledge alert), "add\_alert\_note" (document findings), "generate\_alert\_link" (share with team).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific alert in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete alert details: alert message, severity, threshold crossed, current value, alert history, escalation chain triggered, acknowledgement details, resource details, datasource/datapoint info, alert rule applied. 

**When to use:** 
- Investigate specific alert after getting ID from "list\_alerts"
- Check threshold and current values
- Review alert history and escalation
- Get context before acknowledging

**Workflow:** First use "list\_alerts" to find the alertId, then use this tool for complete investigation details. 

**Related tools:** "acknowledge\_alert" (acknowledge alert), "add\_alert\_note" (document findings), "generate\_alert\_link" (share with team).
      leogallego.logicmonitor_mcp.get_alert:
        alertId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_alert"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            alertId=dict(
                type="str",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
            needMessage=dict(
                type="bool",
                default=true,
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
