#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_datasource
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_datasource
short_description: Get detailed information about a specific datasource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete datasource details: name, displayName, description, appliesTo logic, collection method, datapoints (metrics), thresholds, alert rules, polling interval. 

**When to use:** 
- Understand what datasource monitors
- Review alert thresholds
- See collection method (SNMP/WMI/API/script)
- Check datapoint definitions
- Troubleshoot why datasource applies/doesn't apply to device

**Key information returned:** 
- appliesTo: Logic determining which resource/device get this datasource (e.g., "system.hostname =\~\"\*prod\*\"")
- dataSourceType: Collection method (SNMP, WMI, JDBC, API, script)
- dataPoints: List of metrics collected (e.g., CPUBusyPercent, MemoryUsedPercent)
- alertExpr: Threshold formulas (when to alert)
- collectInterval: How often data is collected (seconds)

**Understanding appliesTo logic:** Shows why datasource does/doesn't monitor certain resources/devices. Common patterns: 
- isWindows() - Only Windows resource/device
- system.devicetype == "server" - Only servers
- hasCategory("AWS/EC2") - Only AWS EC2 instances

**Workflow:** Use "list\_datasources" to find dataSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_datasources" (find datasource), "list\_resource\_datasources" (see which resource/device use it).
description:
  - Get detailed information about a specific datasource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete datasource details: name, displayName, description, appliesTo logic, collection method, datapoints (metrics), thresholds, alert rules, polling interval. 

**When to use:** 
- Understand what datasource monitors
- Review alert thresholds
- See collection method (SNMP/WMI/API/script)
- Check datapoint definitions
- Troubleshoot why datasource applies/doesn't apply to device

**Key information returned:** 
- appliesTo: Logic determining which resource/device get this datasource (e.g., "system.hostname =\~\"\*prod\*\"")
- dataSourceType: Collection method (SNMP, WMI, JDBC, API, script)
- dataPoints: List of metrics collected (e.g., CPUBusyPercent, MemoryUsedPercent)
- alertExpr: Threshold formulas (when to alert)
- collectInterval: How often data is collected (seconds)

**Understanding appliesTo logic:** Shows why datasource does/doesn't monitor certain resources/devices. Common patterns: 
- isWindows() - Only Windows resource/device
- system.devicetype == "server" - Only servers
- hasCategory("AWS/EC2") - Only AWS EC2 instances

**Workflow:** Use "list\_datasources" to find dataSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_datasources" (find datasource), "list\_resource\_datasources" (see which resource/device use it).
  - This module wraps the MCP tool 'get_datasource'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  dataSourceId:
    description:
      - The ID of the datasource to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific datasource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete datasource details: name, displayName, description, appliesTo logic, collection method, datapoints (metrics), thresholds, alert rules, polling interval. 

**When to use:** 
- Understand what datasource monitors
- Review alert thresholds
- See collection method (SNMP/WMI/API/script)
- Check datapoint definitions
- Troubleshoot why datasource applies/doesn't apply to device

**Key information returned:** 
- appliesTo: Logic determining which resource/device get this datasource (e.g., "system.hostname =\~\"\*prod\*\"")
- dataSourceType: Collection method (SNMP, WMI, JDBC, API, script)
- dataPoints: List of metrics collected (e.g., CPUBusyPercent, MemoryUsedPercent)
- alertExpr: Threshold formulas (when to alert)
- collectInterval: How often data is collected (seconds)

**Understanding appliesTo logic:** Shows why datasource does/doesn't monitor certain resources/devices. Common patterns: 
- isWindows() - Only Windows resource/device
- system.devicetype == "server" - Only servers
- hasCategory("AWS/EC2") - Only AWS EC2 instances

**Workflow:** Use "list\_datasources" to find dataSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_datasources" (find datasource), "list\_resource\_datasources" (see which resource/device use it).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific datasource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete datasource details: name, displayName, description, appliesTo logic, collection method, datapoints (metrics), thresholds, alert rules, polling interval. 

**When to use:** 
- Understand what datasource monitors
- Review alert thresholds
- See collection method (SNMP/WMI/API/script)
- Check datapoint definitions
- Troubleshoot why datasource applies/doesn't apply to device

**Key information returned:** 
- appliesTo: Logic determining which resource/device get this datasource (e.g., "system.hostname =\~\"\*prod\*\"")
- dataSourceType: Collection method (SNMP, WMI, JDBC, API, script)
- dataPoints: List of metrics collected (e.g., CPUBusyPercent, MemoryUsedPercent)
- alertExpr: Threshold formulas (when to alert)
- collectInterval: How often data is collected (seconds)

**Understanding appliesTo logic:** Shows why datasource does/doesn't monitor certain resources/devices. Common patterns: 
- isWindows() - Only Windows resource/device
- system.devicetype == "server" - Only servers
- hasCategory("AWS/EC2") - Only AWS EC2 instances

**Workflow:** Use "list\_datasources" to find dataSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_datasources" (find datasource), "list\_resource\_datasources" (see which resource/device use it).
      leogallego.logicmonitor_mcp.get_datasource:
        dataSourceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_datasource"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            dataSourceId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
