#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_recipient
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_recipient
short_description: Get detailed information about a specific recipient by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete recipient details: type, name, contact information (email/phone/URL), notification method, timezone, schedule restrictions, rate limiting settings. 

**When to use:**
- Verify contact information before escalation
- Check notification schedule (business hours vs 24/7)
- Review rate limiting settings
- Audit recipient configuration


**Details returned:** 
- Contact info: Exact email/phone/webhook URL 
- Schedule: When notifications are sent (always vs business hours) 
- Rate limit: Max notifications per time period (prevent notification fatigue) 
- Method: Delivery mechanism (SMTP, Twilio, webhook) 

**Workflow:** Use "list\_recipients" to find recipientId, then use this tool for complete configuration. 

**Related tools:** "list\_recipients" (find recipient), "update\_recipient" (modify), "list\_escalation\_chains" (usage).
description:
  - Get detailed information about a specific recipient by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete recipient details: type, name, contact information (email/phone/URL), notification method, timezone, schedule restrictions, rate limiting settings. 

**When to use:**
- Verify contact information before escalation
- Check notification schedule (business hours vs 24/7)
- Review rate limiting settings
- Audit recipient configuration


**Details returned:** 
- Contact info: Exact email/phone/webhook URL 
- Schedule: When notifications are sent (always vs business hours) 
- Rate limit: Max notifications per time period (prevent notification fatigue) 
- Method: Delivery mechanism (SMTP, Twilio, webhook) 

**Workflow:** Use "list\_recipients" to find recipientId, then use this tool for complete configuration. 

**Related tools:** "list\_recipients" (find recipient), "update\_recipient" (modify), "list\_escalation\_chains" (usage).
  - This module wraps the MCP tool 'get_recipient'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  recipientId:
    description:
      - The ID of the recipient to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific recipient by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete recipient details: type, name, contact information (email/phone/URL), notification method, timezone, schedule restrictions, rate limiting settings. 

**When to use:**
- Verify contact information before escalation
- Check notification schedule (business hours vs 24/7)
- Review rate limiting settings
- Audit recipient configuration


**Details returned:** 
- Contact info: Exact email/phone/webhook URL 
- Schedule: When notifications are sent (always vs business hours) 
- Rate limit: Max notifications per time period (prevent notification fatigue) 
- Method: Delivery mechanism (SMTP, Twilio, webhook) 

**Workflow:** Use "list\_recipients" to find recipientId, then use this tool for complete configuration. 

**Related tools:** "list\_recipients" (find recipient), "update\_recipient" (modify), "list\_escalation\_chains" (usage).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific recipient by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete recipient details: type, name, contact information (email/phone/URL), notification method, timezone, schedule restrictions, rate limiting settings. 

**When to use:**
- Verify contact information before escalation
- Check notification schedule (business hours vs 24/7)
- Review rate limiting settings
- Audit recipient configuration


**Details returned:** 
- Contact info: Exact email/phone/webhook URL 
- Schedule: When notifications are sent (always vs business hours) 
- Rate limit: Max notifications per time period (prevent notification fatigue) 
- Method: Delivery mechanism (SMTP, Twilio, webhook) 

**Workflow:** Use "list\_recipients" to find recipientId, then use this tool for complete configuration. 

**Related tools:** "list\_recipients" (find recipient), "update\_recipient" (modify), "list\_escalation\_chains" (usage).
      leogallego.logicmonitor_mcp.get_recipient:
        recipientId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_recipient"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            recipientId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
