#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_configsource
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_configsource
short_description: Get detailed information about a specific ConfigSource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete ConfigSource details: name, displayName, description, appliesTo logic (which resources/devices), collection method (CLI/SNMP/API), collection script, alert settings. 

**When to use:** 
- Understand what config is being collected
- Review appliesTo logic (why it does/doesn't apply to device)
- Check collection method
- Troubleshoot config collection issues

**Key information:** 
- appliesTo: Logic determining which resource/device get config tracking
- collectMethod: How config is retrieved (CLI commands, SNMP, API)
- configAlerts: Settings for when to alert on changes
- lineageId: Built-in (LogicMonitor) vs custom ConfigSource

**Workflow:** Use "list\_configsources" to find configSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_configsources" (find ConfigSource), "list\_device\_configs" (see configs for device).
description:
  - Get detailed information about a specific ConfigSource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete ConfigSource details: name, displayName, description, appliesTo logic (which resources/devices), collection method (CLI/SNMP/API), collection script, alert settings. 

**When to use:** 
- Understand what config is being collected
- Review appliesTo logic (why it does/doesn't apply to device)
- Check collection method
- Troubleshoot config collection issues

**Key information:** 
- appliesTo: Logic determining which resource/device get config tracking
- collectMethod: How config is retrieved (CLI commands, SNMP, API)
- configAlerts: Settings for when to alert on changes
- lineageId: Built-in (LogicMonitor) vs custom ConfigSource

**Workflow:** Use "list\_configsources" to find configSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_configsources" (find ConfigSource), "list\_device\_configs" (see configs for device).
  - This module wraps the MCP tool 'get_configsource'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  configSourceId:
    description:
      - The ID of the configuration source to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific ConfigSource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete ConfigSource details: name, displayName, description, appliesTo logic (which resources/devices), collection method (CLI/SNMP/API), collection script, alert settings. 

**When to use:** 
- Understand what config is being collected
- Review appliesTo logic (why it does/doesn't apply to device)
- Check collection method
- Troubleshoot config collection issues

**Key information:** 
- appliesTo: Logic determining which resource/device get config tracking
- collectMethod: How config is retrieved (CLI commands, SNMP, API)
- configAlerts: Settings for when to alert on changes
- lineageId: Built-in (LogicMonitor) vs custom ConfigSource

**Workflow:** Use "list\_configsources" to find configSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_configsources" (find ConfigSource), "list\_device\_configs" (see configs for device).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific ConfigSource by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete ConfigSource details: name, displayName, description, appliesTo logic (which resources/devices), collection method (CLI/SNMP/API), collection script, alert settings. 

**When to use:** 
- Understand what config is being collected
- Review appliesTo logic (why it does/doesn't apply to device)
- Check collection method
- Troubleshoot config collection issues

**Key information:** 
- appliesTo: Logic determining which resource/device get config tracking
- collectMethod: How config is retrieved (CLI commands, SNMP, API)
- configAlerts: Settings for when to alert on changes
- lineageId: Built-in (LogicMonitor) vs custom ConfigSource

**Workflow:** Use "list\_configsources" to find configSourceId, then use this tool to understand how it works. 

**Related tools:** "list\_configsources" (find ConfigSource), "list\_device\_configs" (see configs for device).
      leogallego.logicmonitor_mcp.get_configsource:
        configSourceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_configsource"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            configSourceId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
