#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_escalation_chain
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_escalation_chain
short_description: Get detailed information about a specific escalation chain by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete escalation chain details: name, description, all stages with: recipients at each stage, notification methods (email/SMS/webhook), time delays between stages, rate limiting, business hours restrictions. 

**When to use:**
- Review detailed notification workflow
- Verify who gets notified at each stage
- Check timing between escalations
- Audit notification methods
- Troubleshoot why notifications not received


**Stage details returned:** For each stage: 
- Stage number (1, 2, 3...) 
- Delay before stage triggers (minutes) 
- Recipients/groups notified 
- Notification methods (email, SMS, integration) 
- Schedule (24/7 vs business hours only) 

**Example escalation chain details:** Stage 1 (0 min): Email "oncall@company.com", SMS "+1-555-1234" Stage 2 (15 min): PagerDuty integration, Email "team-lead@company.com" Stage 3 (30 min): Slack webhook, Email "engineering-manager@company.com" 

**Workflow:** Use "list\_escalation\_chains" to find chainId, then use this tool to review complete notification workflow. 

**Related tools:** "list\_escalation\_chains" (find chains), "update\_escalation\_chain" (modify), "list\_recipients" (see recipients).
description:
  - Get detailed information about a specific escalation chain by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete escalation chain details: name, description, all stages with: recipients at each stage, notification methods (email/SMS/webhook), time delays between stages, rate limiting, business hours restrictions. 

**When to use:**
- Review detailed notification workflow
- Verify who gets notified at each stage
- Check timing between escalations
- Audit notification methods
- Troubleshoot why notifications not received


**Stage details returned:** For each stage: 
- Stage number (1, 2, 3...) 
- Delay before stage triggers (minutes) 
- Recipients/groups notified 
- Notification methods (email, SMS, integration) 
- Schedule (24/7 vs business hours only) 

**Example escalation chain details:** Stage 1 (0 min): Email "oncall@company.com", SMS "+1-555-1234" Stage 2 (15 min): PagerDuty integration, Email "team-lead@company.com" Stage 3 (30 min): Slack webhook, Email "engineering-manager@company.com" 

**Workflow:** Use "list\_escalation\_chains" to find chainId, then use this tool to review complete notification workflow. 

**Related tools:** "list\_escalation\_chains" (find chains), "update\_escalation\_chain" (modify), "list\_recipients" (see recipients).
  - This module wraps the MCP tool 'get_escalation_chain'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  chainId:
    description:
      - The ID of the escalation chain to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific escalation chain by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete escalation chain details: name, description, all stages with: recipients at each stage, notification methods (email/SMS/webhook), time delays between stages, rate limiting, business hours restrictions. 

**When to use:**
- Review detailed notification workflow
- Verify who gets notified at each stage
- Check timing between escalations
- Audit notification methods
- Troubleshoot why notifications not received


**Stage details returned:** For each stage: 
- Stage number (1, 2, 3...) 
- Delay before stage triggers (minutes) 
- Recipients/groups notified 
- Notification methods (email, SMS, integration) 
- Schedule (24/7 vs business hours only) 

**Example escalation chain details:** Stage 1 (0 min): Email "oncall@company.com", SMS "+1-555-1234" Stage 2 (15 min): PagerDuty integration, Email "team-lead@company.com" Stage 3 (30 min): Slack webhook, Email "engineering-manager@company.com" 

**Workflow:** Use "list\_escalation\_chains" to find chainId, then use this tool to review complete notification workflow. 

**Related tools:** "list\_escalation\_chains" (find chains), "update\_escalation\_chain" (modify), "list\_recipients" (see recipients).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific escalation chain by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete escalation chain details: name, description, all stages with: recipients at each stage, notification methods (email/SMS/webhook), time delays between stages, rate limiting, business hours restrictions. 

**When to use:**
- Review detailed notification workflow
- Verify who gets notified at each stage
- Check timing between escalations
- Audit notification methods
- Troubleshoot why notifications not received


**Stage details returned:** For each stage: 
- Stage number (1, 2, 3...) 
- Delay before stage triggers (minutes) 
- Recipients/groups notified 
- Notification methods (email, SMS, integration) 
- Schedule (24/7 vs business hours only) 

**Example escalation chain details:** Stage 1 (0 min): Email "oncall@company.com", SMS "+1-555-1234" Stage 2 (15 min): PagerDuty integration, Email "team-lead@company.com" Stage 3 (30 min): Slack webhook, Email "engineering-manager@company.com" 

**Workflow:** Use "list\_escalation\_chains" to find chainId, then use this tool to review complete notification workflow. 

**Related tools:** "list\_escalation\_chains" (find chains), "update\_escalation\_chain" (modify), "list\_recipients" (see recipients).
      leogallego.logicmonitor_mcp.get_escalation_chain:
        chainId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_escalation_chain"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            chainId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
