#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_report
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_report
short_description: Get detailed information about a specific report by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete report details: name, type, description, schedule (daily/weekly/monthly), recipients, format, data sources (which resources/devices/groups), date range, customization settings, last run timestamp, delivery status. 

**When to use:** 
- Review report configuration before modification
- Check recipients and schedule
- Verify data sources (which resource/device included)
- Troubleshoot why report not received
- Clone report settings for similar report

**Configuration details:** 
- Schedule: When report runs (e.g., "Every Monday at 8am")
- Recipients: Who receives report via email
- Format: PDF (management), HTML (web), CSV (data analysis)
- Scope: Which resources/devices/groups are included
- Date range: Last 7 days, last month, custom period

**Workflow:** Use "list\_reports" to find reportId, then use this tool for complete configuration. 

**Related tools:** "list\_reports" (find reports), "update\_report" (modify), "generate\_report" (run now).
description:
  - Get detailed information about a specific report by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete report details: name, type, description, schedule (daily/weekly/monthly), recipients, format, data sources (which resources/devices/groups), date range, customization settings, last run timestamp, delivery status. 

**When to use:** 
- Review report configuration before modification
- Check recipients and schedule
- Verify data sources (which resource/device included)
- Troubleshoot why report not received
- Clone report settings for similar report

**Configuration details:** 
- Schedule: When report runs (e.g., "Every Monday at 8am")
- Recipients: Who receives report via email
- Format: PDF (management), HTML (web), CSV (data analysis)
- Scope: Which resources/devices/groups are included
- Date range: Last 7 days, last month, custom period

**Workflow:** Use "list\_reports" to find reportId, then use this tool for complete configuration. 

**Related tools:** "list\_reports" (find reports), "update\_report" (modify), "generate\_report" (run now).
  - This module wraps the MCP tool 'get_report'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  reportId:
    description:
      - The ID of the report to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific report by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete report details: name, type, description, schedule (daily/weekly/monthly), recipients, format, data sources (which resources/devices/groups), date range, customization settings, last run timestamp, delivery status. 

**When to use:** 
- Review report configuration before modification
- Check recipients and schedule
- Verify data sources (which resource/device included)
- Troubleshoot why report not received
- Clone report settings for similar report

**Configuration details:** 
- Schedule: When report runs (e.g., "Every Monday at 8am")
- Recipients: Who receives report via email
- Format: PDF (management), HTML (web), CSV (data analysis)
- Scope: Which resources/devices/groups are included
- Date range: Last 7 days, last month, custom period

**Workflow:** Use "list\_reports" to find reportId, then use this tool for complete configuration. 

**Related tools:** "list\_reports" (find reports), "update\_report" (modify), "generate\_report" (run now).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific report by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete report details: name, type, description, schedule (daily/weekly/monthly), recipients, format, data sources (which resources/devices/groups), date range, customization settings, last run timestamp, delivery status. 

**When to use:** 
- Review report configuration before modification
- Check recipients and schedule
- Verify data sources (which resource/device included)
- Troubleshoot why report not received
- Clone report settings for similar report

**Configuration details:** 
- Schedule: When report runs (e.g., "Every Monday at 8am")
- Recipients: Who receives report via email
- Format: PDF (management), HTML (web), CSV (data analysis)
- Scope: Which resources/devices/groups are included
- Date range: Last 7 days, last month, custom period

**Workflow:** Use "list\_reports" to find reportId, then use this tool for complete configuration. 

**Related tools:** "list\_reports" (find reports), "update\_report" (modify), "generate\_report" (run now).
      leogallego.logicmonitor_mcp.get_report:
        reportId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_report"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            reportId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
