#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_dashboard
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_dashboard
short_description: Get detailed information about a specific dashboard by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete dashboard details: name, description, groupId, owner, widgets configuration, widget count, sharing settings, template variables, last modified. 

**When to use:** 
- Review dashboard configuration
- See widget definitions before cloning
- Check dashboard owner
- Verify template variables
- Get dashboard metadata

**What you get:** 
- widgetsConfig: JSON configuration of all widgets (chart types, metrics, thresholds)
- widgetTokens: Template variables (e.g., defaultDeviceGroup for dynamic filtering)
- groupId/groupName: Which folder dashboard is in
- sharable: Whether dashboard is public/private

**Use cases:** 
- Clone dashboard to create similar one
- Export dashboard configuration for backup
- Audit which resources/devices/metrics are being visualized
- Document dashboard purpose and widgets

**Workflow:** Use "list\_dashboards" to find dashboardId, then get details, then "generate\_dashboard\_link" to get shareable URL. 

**Related tools:** "list\_dashboards" (find dashboard), "generate\_dashboard\_link" (get URL), "update\_dashboard" (modify), "list\_dashboard\_groups" (browse folders).
description:
  - Get detailed information about a specific dashboard by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete dashboard details: name, description, groupId, owner, widgets configuration, widget count, sharing settings, template variables, last modified. 

**When to use:** 
- Review dashboard configuration
- See widget definitions before cloning
- Check dashboard owner
- Verify template variables
- Get dashboard metadata

**What you get:** 
- widgetsConfig: JSON configuration of all widgets (chart types, metrics, thresholds)
- widgetTokens: Template variables (e.g., defaultDeviceGroup for dynamic filtering)
- groupId/groupName: Which folder dashboard is in
- sharable: Whether dashboard is public/private

**Use cases:** 
- Clone dashboard to create similar one
- Export dashboard configuration for backup
- Audit which resources/devices/metrics are being visualized
- Document dashboard purpose and widgets

**Workflow:** Use "list\_dashboards" to find dashboardId, then get details, then "generate\_dashboard\_link" to get shareable URL. 

**Related tools:** "list\_dashboards" (find dashboard), "generate\_dashboard\_link" (get URL), "update\_dashboard" (modify), "list\_dashboard\_groups" (browse folders).
  - This module wraps the MCP tool 'get_dashboard'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  dashboardId:
    description:
      - The ID of the dashboard to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific dashboard by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete dashboard details: name, description, groupId, owner, widgets configuration, widget count, sharing settings, template variables, last modified. 

**When to use:** 
- Review dashboard configuration
- See widget definitions before cloning
- Check dashboard owner
- Verify template variables
- Get dashboard metadata

**What you get:** 
- widgetsConfig: JSON configuration of all widgets (chart types, metrics, thresholds)
- widgetTokens: Template variables (e.g., defaultDeviceGroup for dynamic filtering)
- groupId/groupName: Which folder dashboard is in
- sharable: Whether dashboard is public/private

**Use cases:** 
- Clone dashboard to create similar one
- Export dashboard configuration for backup
- Audit which resources/devices/metrics are being visualized
- Document dashboard purpose and widgets

**Workflow:** Use "list\_dashboards" to find dashboardId, then get details, then "generate\_dashboard\_link" to get shareable URL. 

**Related tools:** "list\_dashboards" (find dashboard), "generate\_dashboard\_link" (get URL), "update\_dashboard" (modify), "list\_dashboard\_groups" (browse folders).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific dashboard by its ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete dashboard details: name, description, groupId, owner, widgets configuration, widget count, sharing settings, template variables, last modified. 

**When to use:** 
- Review dashboard configuration
- See widget definitions before cloning
- Check dashboard owner
- Verify template variables
- Get dashboard metadata

**What you get:** 
- widgetsConfig: JSON configuration of all widgets (chart types, metrics, thresholds)
- widgetTokens: Template variables (e.g., defaultDeviceGroup for dynamic filtering)
- groupId/groupName: Which folder dashboard is in
- sharable: Whether dashboard is public/private

**Use cases:** 
- Clone dashboard to create similar one
- Export dashboard configuration for backup
- Audit which resources/devices/metrics are being visualized
- Document dashboard purpose and widgets

**Workflow:** Use "list\_dashboards" to find dashboardId, then get details, then "generate\_dashboard\_link" to get shareable URL. 

**Related tools:** "list\_dashboards" (find dashboard), "generate\_dashboard\_link" (get URL), "update\_dashboard" (modify), "list\_dashboard\_groups" (browse folders).
      leogallego.logicmonitor_mcp.get_dashboard:
        dashboardId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_dashboard"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            dashboardId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
