#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_resource
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_resource
short_description: Get detailed information about a specific resource/device in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete resource/device details including: displayName, IP/hostname, hostStatus, alertStatus, collector assignment, resource/device type, custom properties, applied datasources, group memberships, last data time, creation date. 

**When to use:** 
- Get full details after finding resource/device ID via "list\_resources"
- Check resource/device configuration
- Verify collector assignment
- Review custom properties before updating

**Workflow:** Use "list\_resources" or "search\_resources" first to find the deviceId, then use this tool for complete details. 

**Related tools:** "list\_resource\_datasources" (see what's monitored), "list\_resource\_properties" (view all properties), "generate\_resource\_link" (get UI link).
description:
  - Get detailed information about a specific resource/device in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete resource/device details including: displayName, IP/hostname, hostStatus, alertStatus, collector assignment, resource/device type, custom properties, applied datasources, group memberships, last data time, creation date. 

**When to use:** 
- Get full details after finding resource/device ID via "list\_resources"
- Check resource/device configuration
- Verify collector assignment
- Review custom properties before updating

**Workflow:** Use "list\_resources" or "search\_resources" first to find the deviceId, then use this tool for complete details. 

**Related tools:** "list\_resource\_datasources" (see what's monitored), "list\_resource\_properties" (view all properties), "generate\_resource\_link" (get UI link).
  - This module wraps the MCP tool 'get_resource'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  deviceId:
    description:
      - The ID of the resource/device to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific resource/device in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete resource/device details including: displayName, IP/hostname, hostStatus, alertStatus, collector assignment, resource/device type, custom properties, applied datasources, group memberships, last data time, creation date. 

**When to use:** 
- Get full details after finding resource/device ID via "list\_resources"
- Check resource/device configuration
- Verify collector assignment
- Review custom properties before updating

**Workflow:** Use "list\_resources" or "search\_resources" first to find the deviceId, then use this tool for complete details. 

**Related tools:** "list\_resource\_datasources" (see what's monitored), "list\_resource\_properties" (view all properties), "generate\_resource\_link" (get UI link).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific resource/device in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete resource/device details including: displayName, IP/hostname, hostStatus, alertStatus, collector assignment, resource/device type, custom properties, applied datasources, group memberships, last data time, creation date. 

**When to use:** 
- Get full details after finding resource/device ID via "list\_resources"
- Check resource/device configuration
- Verify collector assignment
- Review custom properties before updating

**Workflow:** Use "list\_resources" or "search\_resources" first to find the deviceId, then use this tool for complete details. 

**Related tools:** "list\_resource\_datasources" (see what's monitored), "list\_resource\_properties" (view all properties), "generate\_resource\_link" (get UI link).
      leogallego.logicmonitor_mcp.get_resource:
        deviceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_resource"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            deviceId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
