#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_resource_instance_data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_resource_instance_data
short_description: Get time-series metrics/datapoints data (e.g., CPU/memory/network utilization) for a specific resource/device datasource instance in LogicMonitor (LM) monitoring. 

**Returns:** Time-series data with timestamps and values for requested datapoints. Format: {timestamps: [epoch1, epoch2], values: {datapoint1: [val1, val2], datapoint2: [val1, val2]}}. 

**When to use:** 
- Get CPU utilization for last 24 hours
- Fetch disk usage trends
- Retrieve network bandwidth data
- Export metrics for analysis
- Build custom dashboards/reports

**Required workflow (3 steps):** 
- Use "list\_resource\_datasources" → get deviceDataSourceId for datasource (e.g., WinCPU)
- Use "list\_resource\_instances" → get instanceId for specific instance (e.g., CPU Core 0)
- Use this tool → get actual metric values for that instance

**Parameters:** 
- deviceId: Device ID from "get\_resource" or "list\_resources"
- deviceDataSourceId: From "get\_resource\_datasource" or "list\_resource\_datasources"
- instanceId: From "list\_resource\_instances"
- datapoints: Comma-separated metric names (e.g., "CPUBusyPercent,MemoryUsedPercent")
- start/end: Time range in epoch milliseconds (not seconds!), start time must be before current time

**Example:** Get last hour CPU data: start=Date.now()-3600000, end=Date.now() 

**Time range tips:** If omitted, returns last 2 hours. Max range: 1 year. Use shorter ranges for better performance. 

**Related tools:** "list\_resource\_datasources", "list\_resource\_instances".
description:
  - Get time-series metrics/datapoints data (e.g., CPU/memory/network utilization) for a specific resource/device datasource instance in LogicMonitor (LM) monitoring. 

**Returns:** Time-series data with timestamps and values for requested datapoints. Format: {timestamps: [epoch1, epoch2], values: {datapoint1: [val1, val2], datapoint2: [val1, val2]}}. 

**When to use:** 
- Get CPU utilization for last 24 hours
- Fetch disk usage trends
- Retrieve network bandwidth data
- Export metrics for analysis
- Build custom dashboards/reports

**Required workflow (3 steps):** 
- Use "list\_resource\_datasources" → get deviceDataSourceId for datasource (e.g., WinCPU)
- Use "list\_resource\_instances" → get instanceId for specific instance (e.g., CPU Core 0)
- Use this tool → get actual metric values for that instance

**Parameters:** 
- deviceId: Device ID from "get\_resource" or "list\_resources"
- deviceDataSourceId: From "get\_resource\_datasource" or "list\_resource\_datasources"
- instanceId: From "list\_resource\_instances"
- datapoints: Comma-separated metric names (e.g., "CPUBusyPercent,MemoryUsedPercent")
- start/end: Time range in epoch milliseconds (not seconds!), start time must be before current time

**Example:** Get last hour CPU data: start=Date.now()-3600000, end=Date.now() 

**Time range tips:** If omitted, returns last 2 hours. Max range: 1 year. Use shorter ranges for better performance. 

**Related tools:** "list\_resource\_datasources", "list\_resource\_instances".
  - This module wraps the MCP tool 'get_resource_instance_data'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  deviceDataSourceId:
    description:
      - The resource/device datasource ID
    type: float
    required: true
  deviceId:
    description:
      - The resource/device ID
    type: float
    required: true
  instanceId:
    description:
      - The instance ID
    type: float
    required: true
  datapoints:
    description:
      - Comma-separated list of metric/datapoint names
    type: str
    required: false
  end:
    description:
      - End time (epoch milliseconds)
    type: float
    required: false
  format:
    description:
      - Response format: "json" or "csv"
    type: str
    required: false
  start:
    description:
      - Start time (epoch milliseconds), start time must be before current time
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get time-series metrics/datapoints data (e.g., CPU/memory/network utilization) for a specific resource/device datasource instance in LogicMonitor (LM) monitoring. 

**Returns:** Time-series data with timestamps and values for requested datapoints. Format: {timestamps: [epoch1, epoch2], values: {datapoint1: [val1, val2], datapoint2: [val1, val2]}}. 

**When to use:** 
- Get CPU utilization for last 24 hours
- Fetch disk usage trends
- Retrieve network bandwidth data
- Export metrics for analysis
- Build custom dashboards/reports

**Required workflow (3 steps):** 
- Use "list\_resource\_datasources" → get deviceDataSourceId for datasource (e.g., WinCPU)
- Use "list\_resource\_instances" → get instanceId for specific instance (e.g., CPU Core 0)
- Use this tool → get actual metric values for that instance

**Parameters:** 
- deviceId: Device ID from "get\_resource" or "list\_resources"
- deviceDataSourceId: From "get\_resource\_datasource" or "list\_resource\_datasources"
- instanceId: From "list\_resource\_instances"
- datapoints: Comma-separated metric names (e.g., "CPUBusyPercent,MemoryUsedPercent")
- start/end: Time range in epoch milliseconds (not seconds!), start time must be before current time

**Example:** Get last hour CPU data: start=Date.now()-3600000, end=Date.now() 

**Time range tips:** If omitted, returns last 2 hours. Max range: 1 year. Use shorter ranges for better performance. 

**Related tools:** "list\_resource\_datasources", "list\_resource\_instances".
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get time-series metrics/datapoints data (e.g., CPU/memory/network utilization) for a specific resource/device datasource instance in LogicMonitor (LM) monitoring. 

**Returns:** Time-series data with timestamps and values for requested datapoints. Format: {timestamps: [epoch1, epoch2], values: {datapoint1: [val1, val2], datapoint2: [val1, val2]}}. 

**When to use:** 
- Get CPU utilization for last 24 hours
- Fetch disk usage trends
- Retrieve network bandwidth data
- Export metrics for analysis
- Build custom dashboards/reports

**Required workflow (3 steps):** 
- Use "list\_resource\_datasources" → get deviceDataSourceId for datasource (e.g., WinCPU)
- Use "list\_resource\_instances" → get instanceId for specific instance (e.g., CPU Core 0)
- Use this tool → get actual metric values for that instance

**Parameters:** 
- deviceId: Device ID from "get\_resource" or "list\_resources"
- deviceDataSourceId: From "get\_resource\_datasource" or "list\_resource\_datasources"
- instanceId: From "list\_resource\_instances"
- datapoints: Comma-separated metric names (e.g., "CPUBusyPercent,MemoryUsedPercent")
- start/end: Time range in epoch milliseconds (not seconds!), start time must be before current time

**Example:** Get last hour CPU data: start=Date.now()-3600000, end=Date.now() 

**Time range tips:** If omitted, returns last 2 hours. Max range: 1 year. Use shorter ranges for better performance. 

**Related tools:** "list\_resource\_datasources", "list\_resource\_instances".
      leogallego.logicmonitor_mcp.get_resource_instance_data:
        deviceDataSourceId: "CHANGEME"
        deviceId: "CHANGEME"
        instanceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_resource_instance_data"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            deviceDataSourceId=dict(
                type="float",
                required=True,
            ),
            deviceId=dict(
                type="float",
                required=True,
            ),
            instanceId=dict(
                type="float",
                required=True,
            ),
            datapoints=dict(
                type="str",
            ),
            end=dict(
                type="float",
            ),
            format=dict(
                type="str",
            ),
            start=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
