#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_audit_log
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_audit_log
short_description: Get detailed information about a specific audit log entry in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete audit log details: username, IP address, exact timestamp, full description of action, session ID, affected resources, before/after values (for updates). 

**When to use:** 
- Get complete details after finding log ID via "list\_audit\_logs"
- Review exact changes made (old vs new values)
- Investigate specific incident with full context

**Workflow:** First use "list\_audit\_logs" with filters to find relevant entries, then use this tool with the log ID for complete details. 

**Related tools:** "list\_audit\_logs" (search logs), "search\_audit\_logs" (text search).
description:
  - Get detailed information about a specific audit log entry in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete audit log details: username, IP address, exact timestamp, full description of action, session ID, affected resources, before/after values (for updates). 

**When to use:** 
- Get complete details after finding log ID via "list\_audit\_logs"
- Review exact changes made (old vs new values)
- Investigate specific incident with full context

**Workflow:** First use "list\_audit\_logs" with filters to find relevant entries, then use this tool with the log ID for complete details. 

**Related tools:** "list\_audit\_logs" (search logs), "search\_audit\_logs" (text search).
  - This module wraps the MCP tool 'get_audit_log'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  auditLogId:
    description:
      - The ID of the audit log entry to retrieve
    type: str
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific audit log entry in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete audit log details: username, IP address, exact timestamp, full description of action, session ID, affected resources, before/after values (for updates). 

**When to use:** 
- Get complete details after finding log ID via "list\_audit\_logs"
- Review exact changes made (old vs new values)
- Investigate specific incident with full context

**Workflow:** First use "list\_audit\_logs" with filters to find relevant entries, then use this tool with the log ID for complete details. 

**Related tools:** "list\_audit\_logs" (search logs), "search\_audit\_logs" (text search).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific audit log entry in LogicMonitor (LM) monitoring by its ID. 

**Returns:** Complete audit log details: username, IP address, exact timestamp, full description of action, session ID, affected resources, before/after values (for updates). 

**When to use:** 
- Get complete details after finding log ID via "list\_audit\_logs"
- Review exact changes made (old vs new values)
- Investigate specific incident with full context

**Workflow:** First use "list\_audit\_logs" with filters to find relevant entries, then use this tool with the log ID for complete details. 

**Related tools:** "list\_audit\_logs" (search logs), "search\_audit\_logs" (text search).
      leogallego.logicmonitor_mcp.get_audit_log:
        auditLogId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_audit_log"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            auditLogId=dict(
                type="str",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
