#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_resource_datasource
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_resource_datasource
short_description: Get detailed information about a specific datasource applied to a resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Complete resource/device datasource details: dataSourceName, status, alert status, number of instances, monitoring configuration, stop monitoring flag, custom properties, graphs. 

**When to use:**
- Check if datasource is collecting data
- Review alert status for specific datasource
- Verify custom thresholds
- Get deviceDataSourceId for instance operations
- Troubleshoot data collection issues


**Key fields:** 
- instanceNumber: How many instances (e.g., 4 network interfaces) 
- status: Collection status (normal vs error) 
- alertStatus: Any active alerts from this datasource 
- stopMonitoring: Whether datasource is disabled on this resource/device 

**Workflow:** Use "list\_device\_datasources" to find deviceDataSourceId, then use this tool for detailed status. 

**Related tools:** "list\_device\_datasources" (find datasource), "list\_device\_instances" (get instances), "update\_device\_datasource" (enable/disable).
description:
  - Get detailed information about a specific datasource applied to a resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Complete resource/device datasource details: dataSourceName, status, alert status, number of instances, monitoring configuration, stop monitoring flag, custom properties, graphs. 

**When to use:**
- Check if datasource is collecting data
- Review alert status for specific datasource
- Verify custom thresholds
- Get deviceDataSourceId for instance operations
- Troubleshoot data collection issues


**Key fields:** 
- instanceNumber: How many instances (e.g., 4 network interfaces) 
- status: Collection status (normal vs error) 
- alertStatus: Any active alerts from this datasource 
- stopMonitoring: Whether datasource is disabled on this resource/device 

**Workflow:** Use "list\_device\_datasources" to find deviceDataSourceId, then use this tool for detailed status. 

**Related tools:** "list\_device\_datasources" (find datasource), "list\_device\_instances" (get instances), "update\_device\_datasource" (enable/disable).
  - This module wraps the MCP tool 'get_resource_datasource'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  deviceDataSourceId:
    description:
      - The resource/device datasource ID
    type: float
    required: true
  deviceId:
    description:
      - The resource/device ID
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific datasource applied to a resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Complete resource/device datasource details: dataSourceName, status, alert status, number of instances, monitoring configuration, stop monitoring flag, custom properties, graphs. 

**When to use:**
- Check if datasource is collecting data
- Review alert status for specific datasource
- Verify custom thresholds
- Get deviceDataSourceId for instance operations
- Troubleshoot data collection issues


**Key fields:** 
- instanceNumber: How many instances (e.g., 4 network interfaces) 
- status: Collection status (normal vs error) 
- alertStatus: Any active alerts from this datasource 
- stopMonitoring: Whether datasource is disabled on this resource/device 

**Workflow:** Use "list\_device\_datasources" to find deviceDataSourceId, then use this tool for detailed status. 

**Related tools:** "list\_device\_datasources" (find datasource), "list\_device\_instances" (get instances), "update\_device\_datasource" (enable/disable).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific datasource applied to a resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Complete resource/device datasource details: dataSourceName, status, alert status, number of instances, monitoring configuration, stop monitoring flag, custom properties, graphs. 

**When to use:**
- Check if datasource is collecting data
- Review alert status for specific datasource
- Verify custom thresholds
- Get deviceDataSourceId for instance operations
- Troubleshoot data collection issues


**Key fields:** 
- instanceNumber: How many instances (e.g., 4 network interfaces) 
- status: Collection status (normal vs error) 
- alertStatus: Any active alerts from this datasource 
- stopMonitoring: Whether datasource is disabled on this resource/device 

**Workflow:** Use "list\_device\_datasources" to find deviceDataSourceId, then use this tool for detailed status. 

**Related tools:** "list\_device\_datasources" (find datasource), "list\_device\_instances" (get instances), "update\_device\_datasource" (enable/disable).
      leogallego.logicmonitor_mcp.get_resource_datasource:
        deviceDataSourceId: "CHANGEME"
        deviceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_resource_datasource"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            deviceDataSourceId=dict(
                type="float",
                required=True,
            ),
            deviceId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
