#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_opsnote
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_opsnote
short_description: Get detailed information about a specific operational note by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete OpsNote details: note text, timestamp, creator, tags, scope (resources/devices/groups affected), related SDTs, linked resources. 

**When to use:**
- Get full note details after finding ID via list
- Review what was documented at specific time
- Check scope of operational event
- Verify linked resources


**Workflow:** Use "list\_opsnotes" to find note ID, then use this tool for complete details. 

**Related tools:** "list\_opsnotes" (find notes), "create\_opsnote" (add new), "update\_opsnote" (modify).
description:
  - Get detailed information about a specific operational note by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete OpsNote details: note text, timestamp, creator, tags, scope (resources/devices/groups affected), related SDTs, linked resources. 

**When to use:**
- Get full note details after finding ID via list
- Review what was documented at specific time
- Check scope of operational event
- Verify linked resources


**Workflow:** Use "list\_opsnotes" to find note ID, then use this tool for complete details. 

**Related tools:** "list\_opsnotes" (find notes), "create\_opsnote" (add new), "update\_opsnote" (modify).
  - This module wraps the MCP tool 'get_opsnote'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  opsNoteId:
    description:
      - The ID of the OpsNote to retrieve
    type: str
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific operational note by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete OpsNote details: note text, timestamp, creator, tags, scope (resources/devices/groups affected), related SDTs, linked resources. 

**When to use:**
- Get full note details after finding ID via list
- Review what was documented at specific time
- Check scope of operational event
- Verify linked resources


**Workflow:** Use "list\_opsnotes" to find note ID, then use this tool for complete details. 

**Related tools:** "list\_opsnotes" (find notes), "create\_opsnote" (add new), "update\_opsnote" (modify).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific operational note by ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete OpsNote details: note text, timestamp, creator, tags, scope (resources/devices/groups affected), related SDTs, linked resources. 

**When to use:**
- Get full note details after finding ID via list
- Review what was documented at specific time
- Check scope of operational event
- Verify linked resources


**Workflow:** Use "list\_opsnotes" to find note ID, then use this tool for complete details. 

**Related tools:** "list\_opsnotes" (find notes), "create\_opsnote" (add new), "update\_opsnote" (modify).
      leogallego.logicmonitor_mcp.get_opsnote:
        opsNoteId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_opsnote"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            opsNoteId=dict(
                type="str",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
