#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: get_user
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: get_user
short_description: Get detailed information about a specific user by their ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete user details: username, email, firstName, lastName, roles (permissions), status (active/suspended), last login time, created date, phone, timezone, API token count, two-factor auth status. 

**When to use:** 
- Review user permissions and roles
- Check last login time (identify inactive users)
- Verify contact information
- Audit user access before modification
- Get user details for API token management

**Key information:** 
- roles: Array of role names (defines permissions)
- status: "active" (can login) vs "suspended" (access revoked)
- lastLoginOn: Epoch timestamp (identify inactive accounts)
- apiTokens: Number of active API tokens
- twoFAEnabled: Whether 2FA is configured

**Security audit use cases:** 
- Find users who haven't logged in for 90+ days
- Review which users have admin roles
- Check if former employees still have access
- Verify API token usage per user

**Workflow:** Use "list\_users" to find userId, then use this tool for complete user profile. 

**Related tools:** "list\_users" (find user), "list\_roles" (see available roles), "list\_api\_tokens" (view user's tokens), "update\_user" (modify).
description:
  - Get detailed information about a specific user by their ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete user details: username, email, firstName, lastName, roles (permissions), status (active/suspended), last login time, created date, phone, timezone, API token count, two-factor auth status. 

**When to use:** 
- Review user permissions and roles
- Check last login time (identify inactive users)
- Verify contact information
- Audit user access before modification
- Get user details for API token management

**Key information:** 
- roles: Array of role names (defines permissions)
- status: "active" (can login) vs "suspended" (access revoked)
- lastLoginOn: Epoch timestamp (identify inactive accounts)
- apiTokens: Number of active API tokens
- twoFAEnabled: Whether 2FA is configured

**Security audit use cases:** 
- Find users who haven't logged in for 90+ days
- Review which users have admin roles
- Check if former employees still have access
- Verify API token usage per user

**Workflow:** Use "list\_users" to find userId, then use this tool for complete user profile. 

**Related tools:** "list\_users" (find user), "list\_roles" (see available roles), "list\_api\_tokens" (view user's tokens), "update\_user" (modify).
  - This module wraps the MCP tool 'get_user'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  userId:
    description:
      - The ID of the user to retrieve
    type: float
    required: true
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: Get detailed information about a specific user by their ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete user details: username, email, firstName, lastName, roles (permissions), status (active/suspended), last login time, created date, phone, timezone, API token count, two-factor auth status. 

**When to use:** 
- Review user permissions and roles
- Check last login time (identify inactive users)
- Verify contact information
- Audit user access before modification
- Get user details for API token management

**Key information:** 
- roles: Array of role names (defines permissions)
- status: "active" (can login) vs "suspended" (access revoked)
- lastLoginOn: Epoch timestamp (identify inactive accounts)
- apiTokens: Number of active API tokens
- twoFAEnabled: Whether 2FA is configured

**Security audit use cases:** 
- Find users who haven't logged in for 90+ days
- Review which users have admin roles
- Check if former employees still have access
- Verify API token usage per user

**Workflow:** Use "list\_users" to find userId, then use this tool for complete user profile. 

**Related tools:** "list\_users" (find user), "list\_roles" (see available roles), "list\_api\_tokens" (view user's tokens), "update\_user" (modify).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: Get detailed information about a specific user by their ID in LogicMonitor (LM) monitoring. 

**Returns:** Complete user details: username, email, firstName, lastName, roles (permissions), status (active/suspended), last login time, created date, phone, timezone, API token count, two-factor auth status. 

**When to use:** 
- Review user permissions and roles
- Check last login time (identify inactive users)
- Verify contact information
- Audit user access before modification
- Get user details for API token management

**Key information:** 
- roles: Array of role names (defines permissions)
- status: "active" (can login) vs "suspended" (access revoked)
- lastLoginOn: Epoch timestamp (identify inactive accounts)
- apiTokens: Number of active API tokens
- twoFAEnabled: Whether 2FA is configured

**Security audit use cases:** 
- Find users who haven't logged in for 90+ days
- Review which users have admin roles
- Check if former employees still have access
- Verify API token usage per user

**Workflow:** Use "list\_users" to find userId, then use this tool for complete user profile. 

**Related tools:** "list\_users" (find user), "list\_roles" (see available roles), "list\_api\_tokens" (view user's tokens), "update\_user" (modify).
      leogallego.logicmonitor_mcp.get_user:
        userId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "get_user"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            userId=dict(
                type="float",
                required=True,
            ),
            fields=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
