#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_eventsources
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_eventsources
short_description: List all EventSources in LogicMonitor (LM) monitoring. 

**Returns:** Array of EventSources with: id, name, displayName, description, appliesTo logic, event collection method. 

**What are EventSources:** Collect and process event data (logs, Windows events, syslog, traps). Different from DataSources (metrics) and ConfigSources (configs). Used for log monitoring and event correlation. 

**When to use:**
- Find EventSource for log monitoring
- Discover what events are being collected
- Get EventSource IDs for operations
- Audit event monitoring coverage


**Event types collected:** 
- Windows Event Logs: Application, Security, System logs 
- Syslog: Linux/Unix system logs, network resource/device logs 
- SNMP Traps: Network resource/device alerts and notifications 
- Application logs: Custom app logs, web server logs 
- Cloud events: CloudWatch logs, Azure events 

**Common EventSources:** 
- Windows\_Application\_EventLog: Windows application events 
- Windows\_Security\_EventLog: Security/audit logs 
- Linux\_Syslog: Linux system logs via syslog 
- SNMP\_Traps: Network resource/device SNMP traps 
- VMware\_Events: vCenter events 

**Use cases:** 
- Monitor Windows failed login attempts 
- Alert on ERROR/CRITICAL in application logs 
- Collect network resource/device syslog for troubleshooting 
- Track security events for compliance 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_eventsource" (details), "list\_device\_eventsources" (events for device).
description:
  - List all EventSources in LogicMonitor (LM) monitoring. 

**Returns:** Array of EventSources with: id, name, displayName, description, appliesTo logic, event collection method. 

**What are EventSources:** Collect and process event data (logs, Windows events, syslog, traps). Different from DataSources (metrics) and ConfigSources (configs). Used for log monitoring and event correlation. 

**When to use:**
- Find EventSource for log monitoring
- Discover what events are being collected
- Get EventSource IDs for operations
- Audit event monitoring coverage


**Event types collected:** 
- Windows Event Logs: Application, Security, System logs 
- Syslog: Linux/Unix system logs, network resource/device logs 
- SNMP Traps: Network resource/device alerts and notifications 
- Application logs: Custom app logs, web server logs 
- Cloud events: CloudWatch logs, Azure events 

**Common EventSources:** 
- Windows\_Application\_EventLog: Windows application events 
- Windows\_Security\_EventLog: Security/audit logs 
- Linux\_Syslog: Linux system logs via syslog 
- SNMP\_Traps: Network resource/device SNMP traps 
- VMware\_Events: vCenter events 

**Use cases:** 
- Monitor Windows failed login attempts 
- Alert on ERROR/CRITICAL in application logs 
- Collect network resource/device syslog for troubleshooting 
- Track security events for compliance 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_eventsource" (details), "list\_device\_eventsources" (events for device).
  - This module wraps the MCP tool 'list_eventsources'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all EventSources in LogicMonitor (LM) monitoring. 

**Returns:** Array of EventSources with: id, name, displayName, description, appliesTo logic, event collection method. 

**What are EventSources:** Collect and process event data (logs, Windows events, syslog, traps). Different from DataSources (metrics) and ConfigSources (configs). Used for log monitoring and event correlation. 

**When to use:**
- Find EventSource for log monitoring
- Discover what events are being collected
- Get EventSource IDs for operations
- Audit event monitoring coverage


**Event types collected:** 
- Windows Event Logs: Application, Security, System logs 
- Syslog: Linux/Unix system logs, network resource/device logs 
- SNMP Traps: Network resource/device alerts and notifications 
- Application logs: Custom app logs, web server logs 
- Cloud events: CloudWatch logs, Azure events 

**Common EventSources:** 
- Windows\_Application\_EventLog: Windows application events 
- Windows\_Security\_EventLog: Security/audit logs 
- Linux\_Syslog: Linux system logs via syslog 
- SNMP\_Traps: Network resource/device SNMP traps 
- VMware\_Events: vCenter events 

**Use cases:** 
- Monitor Windows failed login attempts 
- Alert on ERROR/CRITICAL in application logs 
- Collect network resource/device syslog for troubleshooting 
- Track security events for compliance 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_eventsource" (details), "list\_device\_eventsources" (events for device).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all EventSources in LogicMonitor (LM) monitoring. 

**Returns:** Array of EventSources with: id, name, displayName, description, appliesTo logic, event collection method. 

**What are EventSources:** Collect and process event data (logs, Windows events, syslog, traps). Different from DataSources (metrics) and ConfigSources (configs). Used for log monitoring and event correlation. 

**When to use:**
- Find EventSource for log monitoring
- Discover what events are being collected
- Get EventSource IDs for operations
- Audit event monitoring coverage


**Event types collected:** 
- Windows Event Logs: Application, Security, System logs 
- Syslog: Linux/Unix system logs, network resource/device logs 
- SNMP Traps: Network resource/device alerts and notifications 
- Application logs: Custom app logs, web server logs 
- Cloud events: CloudWatch logs, Azure events 

**Common EventSources:** 
- Windows\_Application\_EventLog: Windows application events 
- Windows\_Security\_EventLog: Security/audit logs 
- Linux\_Syslog: Linux system logs via syslog 
- SNMP\_Traps: Network resource/device SNMP traps 
- VMware\_Events: vCenter events 

**Use cases:** 
- Monitor Windows failed login attempts 
- Alert on ERROR/CRITICAL in application logs 
- Collect network resource/device syslog for troubleshooting 
- Track security events for compliance 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_eventsource" (details), "list\_device\_eventsources" (events for device).
      leogallego.logicmonitor_mcp.list_eventsources:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_eventsources"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
