#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_roles
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_roles
short_description: List all roles (permission sets) in LogicMonitor (LM) monitoring. 

**Returns:** Array of roles with: id, name, description, custom flag, associated users count, permissions (view/manage/delete for resources/alerts/reports/settings). 

**What are roles:** Permission templates assigned to users. Control who can view/modify/delete resources, alerts, dashboards, settings. Essential for RBAC (role-based access control). 

**When to use:** 
- Discover available roles before creating users
- Audit permission structure
- Find role IDs for user assignment
- Compare custom vs built-in roles
- Compliance documentation

**Built-in roles (examples):** 
- administrator: Full access to everything
- readonly: View-only access to monitoring data
- manager: Manage resources/devices/alerts but not settings

**Custom roles:** Organizations create custom roles for specific needs (e.g., "database-team-role", "view-prod-only"). 

**Common use cases:** 
- "What roles exist?" → List all to see options
- "Who can delete resources/devices?" → Check which roles have delete permissions
- "Create read-only user" → Find "readonly" role ID for user creation

**Workflow:** Use this tool to discover roles, then "get\_role" for detailed permissions, then use in "create\_user" or "update\_user". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_role" (detailed permissions), "list\_users" (see user assignments), "create\_user" (assign roles to new users).
description:
  - List all roles (permission sets) in LogicMonitor (LM) monitoring. 

**Returns:** Array of roles with: id, name, description, custom flag, associated users count, permissions (view/manage/delete for resources/alerts/reports/settings). 

**What are roles:** Permission templates assigned to users. Control who can view/modify/delete resources, alerts, dashboards, settings. Essential for RBAC (role-based access control). 

**When to use:** 
- Discover available roles before creating users
- Audit permission structure
- Find role IDs for user assignment
- Compare custom vs built-in roles
- Compliance documentation

**Built-in roles (examples):** 
- administrator: Full access to everything
- readonly: View-only access to monitoring data
- manager: Manage resources/devices/alerts but not settings

**Custom roles:** Organizations create custom roles for specific needs (e.g., "database-team-role", "view-prod-only"). 

**Common use cases:** 
- "What roles exist?" → List all to see options
- "Who can delete resources/devices?" → Check which roles have delete permissions
- "Create read-only user" → Find "readonly" role ID for user creation

**Workflow:** Use this tool to discover roles, then "get\_role" for detailed permissions, then use in "create\_user" or "update\_user". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_role" (detailed permissions), "list\_users" (see user assignments), "create\_user" (assign roles to new users).
  - This module wraps the MCP tool 'list_roles'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all roles (permission sets) in LogicMonitor (LM) monitoring. 

**Returns:** Array of roles with: id, name, description, custom flag, associated users count, permissions (view/manage/delete for resources/alerts/reports/settings). 

**What are roles:** Permission templates assigned to users. Control who can view/modify/delete resources, alerts, dashboards, settings. Essential for RBAC (role-based access control). 

**When to use:** 
- Discover available roles before creating users
- Audit permission structure
- Find role IDs for user assignment
- Compare custom vs built-in roles
- Compliance documentation

**Built-in roles (examples):** 
- administrator: Full access to everything
- readonly: View-only access to monitoring data
- manager: Manage resources/devices/alerts but not settings

**Custom roles:** Organizations create custom roles for specific needs (e.g., "database-team-role", "view-prod-only"). 

**Common use cases:** 
- "What roles exist?" → List all to see options
- "Who can delete resources/devices?" → Check which roles have delete permissions
- "Create read-only user" → Find "readonly" role ID for user creation

**Workflow:** Use this tool to discover roles, then "get\_role" for detailed permissions, then use in "create\_user" or "update\_user". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_role" (detailed permissions), "list\_users" (see user assignments), "create\_user" (assign roles to new users).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all roles (permission sets) in LogicMonitor (LM) monitoring. 

**Returns:** Array of roles with: id, name, description, custom flag, associated users count, permissions (view/manage/delete for resources/alerts/reports/settings). 

**What are roles:** Permission templates assigned to users. Control who can view/modify/delete resources, alerts, dashboards, settings. Essential for RBAC (role-based access control). 

**When to use:** 
- Discover available roles before creating users
- Audit permission structure
- Find role IDs for user assignment
- Compare custom vs built-in roles
- Compliance documentation

**Built-in roles (examples):** 
- administrator: Full access to everything
- readonly: View-only access to monitoring data
- manager: Manage resources/devices/alerts but not settings

**Custom roles:** Organizations create custom roles for specific needs (e.g., "database-team-role", "view-prod-only"). 

**Common use cases:** 
- "What roles exist?" → List all to see options
- "Who can delete resources/devices?" → Check which roles have delete permissions
- "Create read-only user" → Find "readonly" role ID for user creation

**Workflow:** Use this tool to discover roles, then "get\_role" for detailed permissions, then use in "create\_user" or "update\_user". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_role" (detailed permissions), "list\_users" (see user assignments), "create\_user" (assign roles to new users).
      leogallego.logicmonitor_mcp.list_roles:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_roles"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
