#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_alert_rules
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_alert_rules
short_description: List all alert rules in LogicMonitor (LM) monitoring. 

**Returns:** Array of alert rules with: id, name, priority, enabled status, matching conditions (device/datasource/severity filters), escalation chain assigned, suppression settings. 

**What are alert rules:** The ROUTING LOGIC that determines "which alerts go to which people." Act as traffic directors: "IF alert matches these conditions, THEN send to this escalation chain." Rules are evaluated in priority order (1st match wins). 

**When to use:**
- Audit who gets notified for different alert types
- Understand notification routing logic
- Find rule IDs for modifications
- Troubleshoot "why didn't I get alerted?"
- Document alert notification policies


**How alert rules work:** Alert triggers → Rules evaluated in priority order → First matching rule wins → Routes alert to that rule's escalation chain → Escalation chain notifies recipients 

**Common alert rule patterns:** 
- **Priority 1 (Critical Production):** IF resource/device in "Production" group AND severity = critical → Route to "Critical On-Call" escalation chain 
- **Priority 2 (Database Team):** IF datasource contains "MySQL" OR "PostgreSQL" → Route to "Database Team" escalation chain 
- **Priority 3 (Business Hours):** IF severity = warning → Route to "Business Hours Email" chain (no pages) 
- **Priority 99 (Catch-All):** IF any alert not matched above → Route to "Default NOC" escalation chain 

**Use cases:** 
- "Who gets paged for production CPU alerts?" → Find rule matching prod resources/devices+ CPU datasource 
- "Update team notifications" → Modify alert rule to route to different escalation chain 
- "Stop getting low-priority pages" → Check which rule routes those alerts, adjust severity or chain 

**Critical for notification troubleshooting:** If alerts aren't reaching people, check:
- Does alert match any rule?
- Is matched rule enabled?
- Is escalation chain configured correctly?


**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_alert\_rule" (detailed conditions), "list\_escalation\_chains" (destination chains), "update\_alert\_rule" (modify routing).
description:
  - List all alert rules in LogicMonitor (LM) monitoring. 

**Returns:** Array of alert rules with: id, name, priority, enabled status, matching conditions (device/datasource/severity filters), escalation chain assigned, suppression settings. 

**What are alert rules:** The ROUTING LOGIC that determines "which alerts go to which people." Act as traffic directors: "IF alert matches these conditions, THEN send to this escalation chain." Rules are evaluated in priority order (1st match wins). 

**When to use:**
- Audit who gets notified for different alert types
- Understand notification routing logic
- Find rule IDs for modifications
- Troubleshoot "why didn't I get alerted?"
- Document alert notification policies


**How alert rules work:** Alert triggers → Rules evaluated in priority order → First matching rule wins → Routes alert to that rule's escalation chain → Escalation chain notifies recipients 

**Common alert rule patterns:** 
- **Priority 1 (Critical Production):** IF resource/device in "Production" group AND severity = critical → Route to "Critical On-Call" escalation chain 
- **Priority 2 (Database Team):** IF datasource contains "MySQL" OR "PostgreSQL" → Route to "Database Team" escalation chain 
- **Priority 3 (Business Hours):** IF severity = warning → Route to "Business Hours Email" chain (no pages) 
- **Priority 99 (Catch-All):** IF any alert not matched above → Route to "Default NOC" escalation chain 

**Use cases:** 
- "Who gets paged for production CPU alerts?" → Find rule matching prod resources/devices+ CPU datasource 
- "Update team notifications" → Modify alert rule to route to different escalation chain 
- "Stop getting low-priority pages" → Check which rule routes those alerts, adjust severity or chain 

**Critical for notification troubleshooting:** If alerts aren't reaching people, check:
- Does alert match any rule?
- Is matched rule enabled?
- Is escalation chain configured correctly?


**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_alert\_rule" (detailed conditions), "list\_escalation\_chains" (destination chains), "update\_alert\_rule" (modify routing).
  - This module wraps the MCP tool 'list_alert_rules'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all alert rules in LogicMonitor (LM) monitoring. 

**Returns:** Array of alert rules with: id, name, priority, enabled status, matching conditions (device/datasource/severity filters), escalation chain assigned, suppression settings. 

**What are alert rules:** The ROUTING LOGIC that determines "which alerts go to which people." Act as traffic directors: "IF alert matches these conditions, THEN send to this escalation chain." Rules are evaluated in priority order (1st match wins). 

**When to use:**
- Audit who gets notified for different alert types
- Understand notification routing logic
- Find rule IDs for modifications
- Troubleshoot "why didn't I get alerted?"
- Document alert notification policies


**How alert rules work:** Alert triggers → Rules evaluated in priority order → First matching rule wins → Routes alert to that rule's escalation chain → Escalation chain notifies recipients 

**Common alert rule patterns:** 
- **Priority 1 (Critical Production):** IF resource/device in "Production" group AND severity = critical → Route to "Critical On-Call" escalation chain 
- **Priority 2 (Database Team):** IF datasource contains "MySQL" OR "PostgreSQL" → Route to "Database Team" escalation chain 
- **Priority 3 (Business Hours):** IF severity = warning → Route to "Business Hours Email" chain (no pages) 
- **Priority 99 (Catch-All):** IF any alert not matched above → Route to "Default NOC" escalation chain 

**Use cases:** 
- "Who gets paged for production CPU alerts?" → Find rule matching prod resources/devices+ CPU datasource 
- "Update team notifications" → Modify alert rule to route to different escalation chain 
- "Stop getting low-priority pages" → Check which rule routes those alerts, adjust severity or chain 

**Critical for notification troubleshooting:** If alerts aren't reaching people, check:
- Does alert match any rule?
- Is matched rule enabled?
- Is escalation chain configured correctly?


**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_alert\_rule" (detailed conditions), "list\_escalation\_chains" (destination chains), "update\_alert\_rule" (modify routing).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all alert rules in LogicMonitor (LM) monitoring. 

**Returns:** Array of alert rules with: id, name, priority, enabled status, matching conditions (device/datasource/severity filters), escalation chain assigned, suppression settings. 

**What are alert rules:** The ROUTING LOGIC that determines "which alerts go to which people." Act as traffic directors: "IF alert matches these conditions, THEN send to this escalation chain." Rules are evaluated in priority order (1st match wins). 

**When to use:**
- Audit who gets notified for different alert types
- Understand notification routing logic
- Find rule IDs for modifications
- Troubleshoot "why didn't I get alerted?"
- Document alert notification policies


**How alert rules work:** Alert triggers → Rules evaluated in priority order → First matching rule wins → Routes alert to that rule's escalation chain → Escalation chain notifies recipients 

**Common alert rule patterns:** 
- **Priority 1 (Critical Production):** IF resource/device in "Production" group AND severity = critical → Route to "Critical On-Call" escalation chain 
- **Priority 2 (Database Team):** IF datasource contains "MySQL" OR "PostgreSQL" → Route to "Database Team" escalation chain 
- **Priority 3 (Business Hours):** IF severity = warning → Route to "Business Hours Email" chain (no pages) 
- **Priority 99 (Catch-All):** IF any alert not matched above → Route to "Default NOC" escalation chain 

**Use cases:** 
- "Who gets paged for production CPU alerts?" → Find rule matching prod resources/devices+ CPU datasource 
- "Update team notifications" → Modify alert rule to route to different escalation chain 
- "Stop getting low-priority pages" → Check which rule routes those alerts, adjust severity or chain 

**Critical for notification troubleshooting:** If alerts aren't reaching people, check:
- Does alert match any rule?
- Is matched rule enabled?
- Is escalation chain configured correctly?


**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_alert\_rule" (detailed conditions), "list\_escalation\_chains" (destination chains), "update\_alert\_rule" (modify routing).
      leogallego.logicmonitor_mcp.list_alert_rules:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_alert_rules"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
