#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_resource_group_properties
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_resource_group_properties
short_description: List all custom properties for a specific resource/device group in LogicMonitor (LM) monitoring. Properties set at group level are inherited by all resource/device in the group. 

**Returns:** Array of properties with: name, value, type (custom vs system), and inheritance source. 

**When to use:**
- Review properties before bulk updates
- Audit credentials/settings applied to resource/device group
- Verify property inheritance from parent groups
- Check which properties resource/device will inherit when added to group
- Document group configuration


**What are group properties:** Key-value pairs set at group level that ALL resource/device in the group inherit. Common uses: credentials (SSH/SNMP), environment tags, owner/team info, monitoring settings. 

**Property inheritance:** 
- Properties set on group apply to ALL resource/device in group 
- Child groups inherit from parent groups 
- Device-level properties override group properties 
- Used by datasource "appliesTo" logic and authentication 

**Common group properties:** 
- **Credentials:** ssh.user, ssh.pass, snmp.community, wmi.user, wmi.pass 
- **Tags:** env (production/staging), location (datacenter), owner (team name) 
- **Business metadata:** cost.center, sla.tier, compliance.level 
- **Monitoring config:** polling.interval, alert.threshold.multiplier 

**Use cases:** 
- Audit credentials: Check which credentials are configured for group 
- Before bulk update: See current values before changing 
- Troubleshoot authentication: Verify credentials applied to resource/device 
- Document configuration: Export group settings 

**Workflow:** Use "list\_resource\_groups" to find groupId, then use this tool to see properties, then "update\_device\_group\_property" to modify. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_group\_property" (modify property), "get\_resource\_group" (group details), "list\_device\_properties" (device-level properties).
description:
  - List all custom properties for a specific resource/device group in LogicMonitor (LM) monitoring. Properties set at group level are inherited by all resource/device in the group. 

**Returns:** Array of properties with: name, value, type (custom vs system), and inheritance source. 

**When to use:**
- Review properties before bulk updates
- Audit credentials/settings applied to resource/device group
- Verify property inheritance from parent groups
- Check which properties resource/device will inherit when added to group
- Document group configuration


**What are group properties:** Key-value pairs set at group level that ALL resource/device in the group inherit. Common uses: credentials (SSH/SNMP), environment tags, owner/team info, monitoring settings. 

**Property inheritance:** 
- Properties set on group apply to ALL resource/device in group 
- Child groups inherit from parent groups 
- Device-level properties override group properties 
- Used by datasource "appliesTo" logic and authentication 

**Common group properties:** 
- **Credentials:** ssh.user, ssh.pass, snmp.community, wmi.user, wmi.pass 
- **Tags:** env (production/staging), location (datacenter), owner (team name) 
- **Business metadata:** cost.center, sla.tier, compliance.level 
- **Monitoring config:** polling.interval, alert.threshold.multiplier 

**Use cases:** 
- Audit credentials: Check which credentials are configured for group 
- Before bulk update: See current values before changing 
- Troubleshoot authentication: Verify credentials applied to resource/device 
- Document configuration: Export group settings 

**Workflow:** Use "list\_resource\_groups" to find groupId, then use this tool to see properties, then "update\_device\_group\_property" to modify. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_group\_property" (modify property), "get\_resource\_group" (group details), "list\_device\_properties" (device-level properties).
  - This module wraps the MCP tool 'list_resource_group_properties'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  groupId:
    description:
      - The resource/device group ID
    type: float
    required: true
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all custom properties for a specific resource/device group in LogicMonitor (LM) monitoring. Properties set at group level are inherited by all resource/device in the group. 

**Returns:** Array of properties with: name, value, type (custom vs system), and inheritance source. 

**When to use:**
- Review properties before bulk updates
- Audit credentials/settings applied to resource/device group
- Verify property inheritance from parent groups
- Check which properties resource/device will inherit when added to group
- Document group configuration


**What are group properties:** Key-value pairs set at group level that ALL resource/device in the group inherit. Common uses: credentials (SSH/SNMP), environment tags, owner/team info, monitoring settings. 

**Property inheritance:** 
- Properties set on group apply to ALL resource/device in group 
- Child groups inherit from parent groups 
- Device-level properties override group properties 
- Used by datasource "appliesTo" logic and authentication 

**Common group properties:** 
- **Credentials:** ssh.user, ssh.pass, snmp.community, wmi.user, wmi.pass 
- **Tags:** env (production/staging), location (datacenter), owner (team name) 
- **Business metadata:** cost.center, sla.tier, compliance.level 
- **Monitoring config:** polling.interval, alert.threshold.multiplier 

**Use cases:** 
- Audit credentials: Check which credentials are configured for group 
- Before bulk update: See current values before changing 
- Troubleshoot authentication: Verify credentials applied to resource/device 
- Document configuration: Export group settings 

**Workflow:** Use "list\_resource\_groups" to find groupId, then use this tool to see properties, then "update\_device\_group\_property" to modify. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_group\_property" (modify property), "get\_resource\_group" (group details), "list\_device\_properties" (device-level properties).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all custom properties for a specific resource/device group in LogicMonitor (LM) monitoring. Properties set at group level are inherited by all resource/device in the group. 

**Returns:** Array of properties with: name, value, type (custom vs system), and inheritance source. 

**When to use:**
- Review properties before bulk updates
- Audit credentials/settings applied to resource/device group
- Verify property inheritance from parent groups
- Check which properties resource/device will inherit when added to group
- Document group configuration


**What are group properties:** Key-value pairs set at group level that ALL resource/device in the group inherit. Common uses: credentials (SSH/SNMP), environment tags, owner/team info, monitoring settings. 

**Property inheritance:** 
- Properties set on group apply to ALL resource/device in group 
- Child groups inherit from parent groups 
- Device-level properties override group properties 
- Used by datasource "appliesTo" logic and authentication 

**Common group properties:** 
- **Credentials:** ssh.user, ssh.pass, snmp.community, wmi.user, wmi.pass 
- **Tags:** env (production/staging), location (datacenter), owner (team name) 
- **Business metadata:** cost.center, sla.tier, compliance.level 
- **Monitoring config:** polling.interval, alert.threshold.multiplier 

**Use cases:** 
- Audit credentials: Check which credentials are configured for group 
- Before bulk update: See current values before changing 
- Troubleshoot authentication: Verify credentials applied to resource/device 
- Document configuration: Export group settings 

**Workflow:** Use "list\_resource\_groups" to find groupId, then use this tool to see properties, then "update\_device\_group\_property" to modify. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_group\_property" (modify property), "get\_resource\_group" (group details), "list\_device\_properties" (device-level properties).
      leogallego.logicmonitor_mcp.list_resource_group_properties:
        groupId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_resource_group_properties"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            groupId=dict(
                type="float",
                required=True,
            ),
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
