#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_audit_logs
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_audit_logs
short_description: List audit logs in LogicMonitor (LM) monitoring for compliance and security auditing. 

**Returns:** Array of audit log entries with: id, username, IP address, timestamp (happenedOn in epoch SECONDS), description of action performed, sessionId. 

**When to use:** 
- Investigate changes: "Who deleted this resource/device?" → filter:"description~\*Delete\*,description~\*device\*"
- Track user activity: "What did john.doe do today?" → filter:"username:john.doe,happenedOn>1730851200"
- Monitor API usage: Find actions performed via API tokens
- Compliance audits: Export log history for specific time periods
- Security investigation: Track login attempts, IP addresses, suspicious activities
- Troubleshooting: "Who changed this alert rule?" → filter:"description~\*AlertRule\*"

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"john.doe", query:"device") - searches across username, description, and IP fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"username:admin,happenedOn>1640995200") for precise control

**Common filter patterns:** 
- By user: filter:"username:john.doe"
- By time: filter:"happenedOn>1640995200" (IMPORTANT: epoch SECONDS, not milliseconds!)
- By action type: filter:"description~\*Create\*" or filter:"description~\*Delete\*" or filter:"description~\*Update\*"
- By resource: filter:"description~\*device\*" or filter:"description~\*dashboard\*"
- By IP: filter:"ip:192.168.1.100"
- Combined (AND): filter:"username:admin,happenedOn>1640995200,description~\*device\*"

**Query vs Filter:** 
- query: Simple text search across username, description, IP (OR logic). Use for quick lookups: query:"john.doe", query:"device"
- filter: Precise LM filter syntax with any field. Use for time ranges, exact matches: filter:"happenedOn>1640995200"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Critical notes:** 
- Time uses epoch SECONDS (not milliseconds like other LM APIs)
- Cannot use OR operator (||) in audit logs, only AND (comma)
- Use autoPaginate:true for complete history (may take time for large datasets)

**Web UI access:** https://test.logicmonitor.com/santaba/uiv4/settings/access-logs (Settings → Audit Logs) 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_audit\_log" (details of specific entry).
description:
  - List audit logs in LogicMonitor (LM) monitoring for compliance and security auditing. 

**Returns:** Array of audit log entries with: id, username, IP address, timestamp (happenedOn in epoch SECONDS), description of action performed, sessionId. 

**When to use:** 
- Investigate changes: "Who deleted this resource/device?" → filter:"description~\*Delete\*,description~\*device\*"
- Track user activity: "What did john.doe do today?" → filter:"username:john.doe,happenedOn>1730851200"
- Monitor API usage: Find actions performed via API tokens
- Compliance audits: Export log history for specific time periods
- Security investigation: Track login attempts, IP addresses, suspicious activities
- Troubleshooting: "Who changed this alert rule?" → filter:"description~\*AlertRule\*"

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"john.doe", query:"device") - searches across username, description, and IP fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"username:admin,happenedOn>1640995200") for precise control

**Common filter patterns:** 
- By user: filter:"username:john.doe"
- By time: filter:"happenedOn>1640995200" (IMPORTANT: epoch SECONDS, not milliseconds!)
- By action type: filter:"description~\*Create\*" or filter:"description~\*Delete\*" or filter:"description~\*Update\*"
- By resource: filter:"description~\*device\*" or filter:"description~\*dashboard\*"
- By IP: filter:"ip:192.168.1.100"
- Combined (AND): filter:"username:admin,happenedOn>1640995200,description~\*device\*"

**Query vs Filter:** 
- query: Simple text search across username, description, IP (OR logic). Use for quick lookups: query:"john.doe", query:"device"
- filter: Precise LM filter syntax with any field. Use for time ranges, exact matches: filter:"happenedOn>1640995200"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Critical notes:** 
- Time uses epoch SECONDS (not milliseconds like other LM APIs)
- Cannot use OR operator (||) in audit logs, only AND (comma)
- Use autoPaginate:true for complete history (may take time for large datasets)

**Web UI access:** https://test.logicmonitor.com/santaba/uiv4/settings/access-logs (Settings → Audit Logs) 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_audit\_log" (details of specific entry).
  - This module wraps the MCP tool 'list_audit_logs'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  query:
    description:
      - Simple search query. Free text (e.g., "john.doe", "device", "192.168.1.100") automatically searches across username, description, and IP fields. Can also use filter syntax (e.g., "username:admin") which gets formatted automatically.
    type: str
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List audit logs in LogicMonitor (LM) monitoring for compliance and security auditing. 

**Returns:** Array of audit log entries with: id, username, IP address, timestamp (happenedOn in epoch SECONDS), description of action performed, sessionId. 

**When to use:** 
- Investigate changes: "Who deleted this resource/device?" → filter:"description~\*Delete\*,description~\*device\*"
- Track user activity: "What did john.doe do today?" → filter:"username:john.doe,happenedOn>1730851200"
- Monitor API usage: Find actions performed via API tokens
- Compliance audits: Export log history for specific time periods
- Security investigation: Track login attempts, IP addresses, suspicious activities
- Troubleshooting: "Who changed this alert rule?" → filter:"description~\*AlertRule\*"

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"john.doe", query:"device") - searches across username, description, and IP fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"username:admin,happenedOn>1640995200") for precise control

**Common filter patterns:** 
- By user: filter:"username:john.doe"
- By time: filter:"happenedOn>1640995200" (IMPORTANT: epoch SECONDS, not milliseconds!)
- By action type: filter:"description~\*Create\*" or filter:"description~\*Delete\*" or filter:"description~\*Update\*"
- By resource: filter:"description~\*device\*" or filter:"description~\*dashboard\*"
- By IP: filter:"ip:192.168.1.100"
- Combined (AND): filter:"username:admin,happenedOn>1640995200,description~\*device\*"

**Query vs Filter:** 
- query: Simple text search across username, description, IP (OR logic). Use for quick lookups: query:"john.doe", query:"device"
- filter: Precise LM filter syntax with any field. Use for time ranges, exact matches: filter:"happenedOn>1640995200"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Critical notes:** 
- Time uses epoch SECONDS (not milliseconds like other LM APIs)
- Cannot use OR operator (||) in audit logs, only AND (comma)
- Use autoPaginate:true for complete history (may take time for large datasets)

**Web UI access:** https://test.logicmonitor.com/santaba/uiv4/settings/access-logs (Settings → Audit Logs) 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_audit\_log" (details of specific entry).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List audit logs in LogicMonitor (LM) monitoring for compliance and security auditing. 

**Returns:** Array of audit log entries with: id, username, IP address, timestamp (happenedOn in epoch SECONDS), description of action performed, sessionId. 

**When to use:** 
- Investigate changes: "Who deleted this resource/device?" → filter:"description~\*Delete\*,description~\*device\*"
- Track user activity: "What did john.doe do today?" → filter:"username:john.doe,happenedOn>1730851200"
- Monitor API usage: Find actions performed via API tokens
- Compliance audits: Export log history for specific time periods
- Security investigation: Track login attempts, IP addresses, suspicious activities
- Troubleshooting: "Who changed this alert rule?" → filter:"description~\*AlertRule\*"

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"john.doe", query:"device") - searches across username, description, and IP fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"username:admin,happenedOn>1640995200") for precise control

**Common filter patterns:** 
- By user: filter:"username:john.doe"
- By time: filter:"happenedOn>1640995200" (IMPORTANT: epoch SECONDS, not milliseconds!)
- By action type: filter:"description~\*Create\*" or filter:"description~\*Delete\*" or filter:"description~\*Update\*"
- By resource: filter:"description~\*device\*" or filter:"description~\*dashboard\*"
- By IP: filter:"ip:192.168.1.100"
- Combined (AND): filter:"username:admin,happenedOn>1640995200,description~\*device\*"

**Query vs Filter:** 
- query: Simple text search across username, description, IP (OR logic). Use for quick lookups: query:"john.doe", query:"device"
- filter: Precise LM filter syntax with any field. Use for time ranges, exact matches: filter:"happenedOn>1640995200"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Critical notes:** 
- Time uses epoch SECONDS (not milliseconds like other LM APIs)
- Cannot use OR operator (||) in audit logs, only AND (comma)
- Use autoPaginate:true for complete history (may take time for large datasets)

**Web UI access:** https://test.logicmonitor.com/santaba/uiv4/settings/access-logs (Settings → Audit Logs) 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_audit\_log" (details of specific entry).
      leogallego.logicmonitor_mcp.list_audit_logs:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_audit_logs"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            query=dict(
                type="str",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
