#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_collectors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_collectors
short_description: List all LogicMonitor (LM) monitoring collectors (monitoring agents). 

**Returns:** Array of collectors with: id, description (collector name), hostname, platform (Windows/Linux), status (alive/dead), build version, number of monitored resources/devices, last heartbeat time. 

**When to use:** 
- Check collector health status before adding resources/devices
- Find available collectors for new resource/device assignments
- Monitor collector capacity and load
- Identify offline/dead collectors

**What are collectors:** Lightweight agents installed on-premise or in cloud that collect metrics from resources/devices. Each resource/device must be assigned to one collector. 

**Common filter patterns:** 
- Alive collectors: filter:"status:alive"
- By platform: filter:"platform:Linux" or filter:"platform:Windows"
- By name: filter:"description\~\*prod\*"
- Low capacity: filter:"numberOfHosts<100"

**Before creating resources/devices:** Use this tool to find collectorId for the "preferredCollectorId" parameter in "create\_resource". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_collector" (details), "list\_collector\_groups" (browse groups), "list\_collector\_versions" (check updates).
description:
  - List all LogicMonitor (LM) monitoring collectors (monitoring agents). 

**Returns:** Array of collectors with: id, description (collector name), hostname, platform (Windows/Linux), status (alive/dead), build version, number of monitored resources/devices, last heartbeat time. 

**When to use:** 
- Check collector health status before adding resources/devices
- Find available collectors for new resource/device assignments
- Monitor collector capacity and load
- Identify offline/dead collectors

**What are collectors:** Lightweight agents installed on-premise or in cloud that collect metrics from resources/devices. Each resource/device must be assigned to one collector. 

**Common filter patterns:** 
- Alive collectors: filter:"status:alive"
- By platform: filter:"platform:Linux" or filter:"platform:Windows"
- By name: filter:"description\~\*prod\*"
- Low capacity: filter:"numberOfHosts<100"

**Before creating resources/devices:** Use this tool to find collectorId for the "preferredCollectorId" parameter in "create\_resource". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_collector" (details), "list\_collector\_groups" (browse groups), "list\_collector\_versions" (check updates).
  - This module wraps the MCP tool 'list_collectors'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all LogicMonitor (LM) monitoring collectors (monitoring agents). 

**Returns:** Array of collectors with: id, description (collector name), hostname, platform (Windows/Linux), status (alive/dead), build version, number of monitored resources/devices, last heartbeat time. 

**When to use:** 
- Check collector health status before adding resources/devices
- Find available collectors for new resource/device assignments
- Monitor collector capacity and load
- Identify offline/dead collectors

**What are collectors:** Lightweight agents installed on-premise or in cloud that collect metrics from resources/devices. Each resource/device must be assigned to one collector. 

**Common filter patterns:** 
- Alive collectors: filter:"status:alive"
- By platform: filter:"platform:Linux" or filter:"platform:Windows"
- By name: filter:"description\~\*prod\*"
- Low capacity: filter:"numberOfHosts<100"

**Before creating resources/devices:** Use this tool to find collectorId for the "preferredCollectorId" parameter in "create\_resource". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_collector" (details), "list\_collector\_groups" (browse groups), "list\_collector\_versions" (check updates).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all LogicMonitor (LM) monitoring collectors (monitoring agents). 

**Returns:** Array of collectors with: id, description (collector name), hostname, platform (Windows/Linux), status (alive/dead), build version, number of monitored resources/devices, last heartbeat time. 

**When to use:** 
- Check collector health status before adding resources/devices
- Find available collectors for new resource/device assignments
- Monitor collector capacity and load
- Identify offline/dead collectors

**What are collectors:** Lightweight agents installed on-premise or in cloud that collect metrics from resources/devices. Each resource/device must be assigned to one collector. 

**Common filter patterns:** 
- Alive collectors: filter:"status:alive"
- By platform: filter:"platform:Linux" or filter:"platform:Windows"
- By name: filter:"description\~\*prod\*"
- Low capacity: filter:"numberOfHosts<100"

**Before creating resources/devices:** Use this tool to find collectorId for the "preferredCollectorId" parameter in "create\_resource". 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_collector" (details), "list\_collector\_groups" (browse groups), "list\_collector\_versions" (check updates).
      leogallego.logicmonitor_mcp.list_collectors:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_collectors"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
