#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_services
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_services
short_description: List all business services in LogicMonitor (LM) monitoring. 

**Returns:** Array of services with: id, name, description, health status, dependencies, monitored resources, service level objectives (SLOs), availability percentage. 

**What are services:** Business-level monitoring constructs that aggregate multiple resources/devices/resources into a single health status. Represent customer-facing services, applications, or business processes. Example: "E-Commerce Platform" service includes web servers, databases, load balancers, and APIs - one health indicator for entire platform. 

**When to use:**
- Monitor business service health vs individual resource/device health
- Track SLA compliance for customer-facing services
- Understand service dependencies
- Create business-level dashboards
- Report on application availability


**Service health calculation:** Service health = Aggregate of all dependent resources. If critical resource fails, service status = down. Allows stakeholders to see "Is the application working?" instead of "Is server X working?" 

**Use cases and examples:** 

**Customer-facing services:** 
- "E-Commerce Website" - Web servers + database + payment gateway + CDN 
- "Mobile App Backend" - API servers + auth service + push notifications 
- "SaaS Platform" - All infrastructure for multi-tenant application 

**Internal services:** 
- "Employee VPN" - VPN servers + RADIUS auth + firewall 
- "Corporate Email" - Mail servers + spam filter + archiving 
- "CI/CD Pipeline" - Jenkins + artifact storage + deployment agents 

**Benefits:** 
- **Business perspective:** Non-technical stakeholders understand "Shopping Cart is 99.5% available" 
- **SLA tracking:** Measure uptime for customer SLAs 
- **Root cause:** When service is down, see which specific resource failed 
- **Dependencies:** Visualize what resources comprise a service 

**Common filter patterns:** 
- By status: filter:"status:normal" or filter:"status:dead" 
- By name: filter:"name~*production*" 

**Workflow:** Use this tool to find services, then "get\_service" for detailed dependency tree and health status. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_service" (details and dependencies), "list\_service\_groups" (organization), "create\_service" (define new business service).
description:
  - List all business services in LogicMonitor (LM) monitoring. 

**Returns:** Array of services with: id, name, description, health status, dependencies, monitored resources, service level objectives (SLOs), availability percentage. 

**What are services:** Business-level monitoring constructs that aggregate multiple resources/devices/resources into a single health status. Represent customer-facing services, applications, or business processes. Example: "E-Commerce Platform" service includes web servers, databases, load balancers, and APIs - one health indicator for entire platform. 

**When to use:**
- Monitor business service health vs individual resource/device health
- Track SLA compliance for customer-facing services
- Understand service dependencies
- Create business-level dashboards
- Report on application availability


**Service health calculation:** Service health = Aggregate of all dependent resources. If critical resource fails, service status = down. Allows stakeholders to see "Is the application working?" instead of "Is server X working?" 

**Use cases and examples:** 

**Customer-facing services:** 
- "E-Commerce Website" - Web servers + database + payment gateway + CDN 
- "Mobile App Backend" - API servers + auth service + push notifications 
- "SaaS Platform" - All infrastructure for multi-tenant application 

**Internal services:** 
- "Employee VPN" - VPN servers + RADIUS auth + firewall 
- "Corporate Email" - Mail servers + spam filter + archiving 
- "CI/CD Pipeline" - Jenkins + artifact storage + deployment agents 

**Benefits:** 
- **Business perspective:** Non-technical stakeholders understand "Shopping Cart is 99.5% available" 
- **SLA tracking:** Measure uptime for customer SLAs 
- **Root cause:** When service is down, see which specific resource failed 
- **Dependencies:** Visualize what resources comprise a service 

**Common filter patterns:** 
- By status: filter:"status:normal" or filter:"status:dead" 
- By name: filter:"name~*production*" 

**Workflow:** Use this tool to find services, then "get\_service" for detailed dependency tree and health status. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_service" (details and dependencies), "list\_service\_groups" (organization), "create\_service" (define new business service).
  - This module wraps the MCP tool 'list_services'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all business services in LogicMonitor (LM) monitoring. 

**Returns:** Array of services with: id, name, description, health status, dependencies, monitored resources, service level objectives (SLOs), availability percentage. 

**What are services:** Business-level monitoring constructs that aggregate multiple resources/devices/resources into a single health status. Represent customer-facing services, applications, or business processes. Example: "E-Commerce Platform" service includes web servers, databases, load balancers, and APIs - one health indicator for entire platform. 

**When to use:**
- Monitor business service health vs individual resource/device health
- Track SLA compliance for customer-facing services
- Understand service dependencies
- Create business-level dashboards
- Report on application availability


**Service health calculation:** Service health = Aggregate of all dependent resources. If critical resource fails, service status = down. Allows stakeholders to see "Is the application working?" instead of "Is server X working?" 

**Use cases and examples:** 

**Customer-facing services:** 
- "E-Commerce Website" - Web servers + database + payment gateway + CDN 
- "Mobile App Backend" - API servers + auth service + push notifications 
- "SaaS Platform" - All infrastructure for multi-tenant application 

**Internal services:** 
- "Employee VPN" - VPN servers + RADIUS auth + firewall 
- "Corporate Email" - Mail servers + spam filter + archiving 
- "CI/CD Pipeline" - Jenkins + artifact storage + deployment agents 

**Benefits:** 
- **Business perspective:** Non-technical stakeholders understand "Shopping Cart is 99.5% available" 
- **SLA tracking:** Measure uptime for customer SLAs 
- **Root cause:** When service is down, see which specific resource failed 
- **Dependencies:** Visualize what resources comprise a service 

**Common filter patterns:** 
- By status: filter:"status:normal" or filter:"status:dead" 
- By name: filter:"name~*production*" 

**Workflow:** Use this tool to find services, then "get\_service" for detailed dependency tree and health status. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_service" (details and dependencies), "list\_service\_groups" (organization), "create\_service" (define new business service).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all business services in LogicMonitor (LM) monitoring. 

**Returns:** Array of services with: id, name, description, health status, dependencies, monitored resources, service level objectives (SLOs), availability percentage. 

**What are services:** Business-level monitoring constructs that aggregate multiple resources/devices/resources into a single health status. Represent customer-facing services, applications, or business processes. Example: "E-Commerce Platform" service includes web servers, databases, load balancers, and APIs - one health indicator for entire platform. 

**When to use:**
- Monitor business service health vs individual resource/device health
- Track SLA compliance for customer-facing services
- Understand service dependencies
- Create business-level dashboards
- Report on application availability


**Service health calculation:** Service health = Aggregate of all dependent resources. If critical resource fails, service status = down. Allows stakeholders to see "Is the application working?" instead of "Is server X working?" 

**Use cases and examples:** 

**Customer-facing services:** 
- "E-Commerce Website" - Web servers + database + payment gateway + CDN 
- "Mobile App Backend" - API servers + auth service + push notifications 
- "SaaS Platform" - All infrastructure for multi-tenant application 

**Internal services:** 
- "Employee VPN" - VPN servers + RADIUS auth + firewall 
- "Corporate Email" - Mail servers + spam filter + archiving 
- "CI/CD Pipeline" - Jenkins + artifact storage + deployment agents 

**Benefits:** 
- **Business perspective:** Non-technical stakeholders understand "Shopping Cart is 99.5% available" 
- **SLA tracking:** Measure uptime for customer SLAs 
- **Root cause:** When service is down, see which specific resource failed 
- **Dependencies:** Visualize what resources comprise a service 

**Common filter patterns:** 
- By status: filter:"status:normal" or filter:"status:dead" 
- By name: filter:"name~*production*" 

**Workflow:** Use this tool to find services, then "get\_service" for detailed dependency tree and health status. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_service" (details and dependencies), "list\_service\_groups" (organization), "create\_service" (define new business service).
      leogallego.logicmonitor_mcp.list_services:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_services"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
