#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_escalation_chains
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_escalation_chains
short_description: List all escalation chains in LogicMonitor (LM) monitoring. 

**Returns:** Array of escalation chains with: id, name, description, escalation stages, recipients at each stage, timing/delays, enabled status. 

**What are escalation chains:** Define HOW and WHO gets notified when alerts trigger. Multi-stage notification workflows: Stage 1 (notify team lead immediately) → Stage 2 (if still open after 15 min, notify manager) → Stage 3 (if still open after 30 min, page director). 

**When to use:**
- Audit notification routing
- Find escalation chain IDs for alert rule configuration
- Review who gets notified for critical alerts
- Verify on-call escalation paths


**How escalation chains work:** Alert triggers → Alert Rule matches → Routes to Escalation Chain → Stage 1 notifies immediately → Wait X minutes → If still alerting, Stage 2 notifies → Repeat through stages 

**Common escalation patterns:** 
- **Critical Production:** Stage 1: On-call engineer (0 min) → Stage 2: Team lead (15 min) → Stage 3: Engineering manager (30 min) 
- **Standard:** Stage 1: Team email (0 min) → Stage 2: PagerDuty (30 min) 
- **Business Hours Only:** Stage 1: Team Slack (0 min, 8am-6pm only) 

**Use cases:** 
- "Who gets paged for critical database alerts?" → Check escalation chain 
- "Why didn't I get notified?" → Verify you're in the escalation chain 
- "Update on-call rotation" → Modify escalation chain recipients 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_escalation\_chain" (detailed stages), "list\_alert\_rules" (see which rules use chain), "list\_recipients" (available notification targets).
description:
  - List all escalation chains in LogicMonitor (LM) monitoring. 

**Returns:** Array of escalation chains with: id, name, description, escalation stages, recipients at each stage, timing/delays, enabled status. 

**What are escalation chains:** Define HOW and WHO gets notified when alerts trigger. Multi-stage notification workflows: Stage 1 (notify team lead immediately) → Stage 2 (if still open after 15 min, notify manager) → Stage 3 (if still open after 30 min, page director). 

**When to use:**
- Audit notification routing
- Find escalation chain IDs for alert rule configuration
- Review who gets notified for critical alerts
- Verify on-call escalation paths


**How escalation chains work:** Alert triggers → Alert Rule matches → Routes to Escalation Chain → Stage 1 notifies immediately → Wait X minutes → If still alerting, Stage 2 notifies → Repeat through stages 

**Common escalation patterns:** 
- **Critical Production:** Stage 1: On-call engineer (0 min) → Stage 2: Team lead (15 min) → Stage 3: Engineering manager (30 min) 
- **Standard:** Stage 1: Team email (0 min) → Stage 2: PagerDuty (30 min) 
- **Business Hours Only:** Stage 1: Team Slack (0 min, 8am-6pm only) 

**Use cases:** 
- "Who gets paged for critical database alerts?" → Check escalation chain 
- "Why didn't I get notified?" → Verify you're in the escalation chain 
- "Update on-call rotation" → Modify escalation chain recipients 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_escalation\_chain" (detailed stages), "list\_alert\_rules" (see which rules use chain), "list\_recipients" (available notification targets).
  - This module wraps the MCP tool 'list_escalation_chains'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all escalation chains in LogicMonitor (LM) monitoring. 

**Returns:** Array of escalation chains with: id, name, description, escalation stages, recipients at each stage, timing/delays, enabled status. 

**What are escalation chains:** Define HOW and WHO gets notified when alerts trigger. Multi-stage notification workflows: Stage 1 (notify team lead immediately) → Stage 2 (if still open after 15 min, notify manager) → Stage 3 (if still open after 30 min, page director). 

**When to use:**
- Audit notification routing
- Find escalation chain IDs for alert rule configuration
- Review who gets notified for critical alerts
- Verify on-call escalation paths


**How escalation chains work:** Alert triggers → Alert Rule matches → Routes to Escalation Chain → Stage 1 notifies immediately → Wait X minutes → If still alerting, Stage 2 notifies → Repeat through stages 

**Common escalation patterns:** 
- **Critical Production:** Stage 1: On-call engineer (0 min) → Stage 2: Team lead (15 min) → Stage 3: Engineering manager (30 min) 
- **Standard:** Stage 1: Team email (0 min) → Stage 2: PagerDuty (30 min) 
- **Business Hours Only:** Stage 1: Team Slack (0 min, 8am-6pm only) 

**Use cases:** 
- "Who gets paged for critical database alerts?" → Check escalation chain 
- "Why didn't I get notified?" → Verify you're in the escalation chain 
- "Update on-call rotation" → Modify escalation chain recipients 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_escalation\_chain" (detailed stages), "list\_alert\_rules" (see which rules use chain), "list\_recipients" (available notification targets).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all escalation chains in LogicMonitor (LM) monitoring. 

**Returns:** Array of escalation chains with: id, name, description, escalation stages, recipients at each stage, timing/delays, enabled status. 

**What are escalation chains:** Define HOW and WHO gets notified when alerts trigger. Multi-stage notification workflows: Stage 1 (notify team lead immediately) → Stage 2 (if still open after 15 min, notify manager) → Stage 3 (if still open after 30 min, page director). 

**When to use:**
- Audit notification routing
- Find escalation chain IDs for alert rule configuration
- Review who gets notified for critical alerts
- Verify on-call escalation paths


**How escalation chains work:** Alert triggers → Alert Rule matches → Routes to Escalation Chain → Stage 1 notifies immediately → Wait X minutes → If still alerting, Stage 2 notifies → Repeat through stages 

**Common escalation patterns:** 
- **Critical Production:** Stage 1: On-call engineer (0 min) → Stage 2: Team lead (15 min) → Stage 3: Engineering manager (30 min) 
- **Standard:** Stage 1: Team email (0 min) → Stage 2: PagerDuty (30 min) 
- **Business Hours Only:** Stage 1: Team Slack (0 min, 8am-6pm only) 

**Use cases:** 
- "Who gets paged for critical database alerts?" → Check escalation chain 
- "Why didn't I get notified?" → Verify you're in the escalation chain 
- "Update on-call rotation" → Modify escalation chain recipients 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_escalation\_chain" (detailed stages), "list\_alert\_rules" (see which rules use chain), "list\_recipients" (available notification targets).
      leogallego.logicmonitor_mcp.list_escalation_chains:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_escalation_chains"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
