#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_netscans
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_netscans
short_description: List all network discovery scans (NetScans) in LogicMonitor (LM) monitoring. 

**Returns:** Array of netscans with: id, name, description, scan method (nmap/script/ICMP/SNMP), schedule, target networks (IP ranges/subnets), collector, last run time, resource/device discovered. 

**What are netscans:** Automated network discovery that finds resource/device on your network and adds them to monitoring. Instead of manually adding resource/device one-by-one, netscan automatically discovers and onboards resource/device based on IP ranges or subnets. 

**When to use:**
- Audit existing discovery configurations
- Check which networks are being scanned
- Review netscan schedules
- Troubleshoot why resource/device not auto-discovered
- Find netscan IDs for modifications


**How netscans work:** Scheduled job → Scan network range (e.g., 192.168.1.0/24) → Find live resource/device → Check if already monitored → If new, add to LogicMonitor → Apply resource/device properties and datasources → Begin monitoring 

**NetScan methods:** 
- **nmap:** Network mapper scan (comprehensive, detects OS, ports, services) 
- **ICMP Ping:** Simple ping sweep (fastest, basic reachability) 
- **SNMP Walk:** Query SNMP-enabled resource/device (network gear, servers with SNMP) 
- **Script:** Custom discovery logic (cloud APIs, CMDBs, etc.) 
- **AWS/Azure/GCP:** Cloud auto-discovery via APIs 

**Common use cases:** 
- **Data center discovery:** Scan 10.0.0.0/16 network, auto-add all servers 
- **Cloud auto-discovery:** Scan AWS account, add all EC2 instances daily 
- **Branch office monitoring:** Scan remote office subnets, discover network resource/device 
- **Dynamic infrastructure:** Auto-discover containers, VMs as they spin up 

**Example NetScan configurations:** 
- "Production Servers" - Scan 192.168.1.0/24 every 6 hours via nmap 
- "AWS EC2 Discovery" - Query AWS API every hour for new instances 
- "Network resources/Devices" - SNMP walk 10.0.0.0/8 daily for routers/switches 

**Workflow:** Use this tool to review netscans, then "get\_netscan" for detailed configuration including filters and resource/device properties. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_netscan" (configuration details), "create\_netscan" (set up auto-discovery), "run\_netscan" (trigger manual scan).
description:
  - List all network discovery scans (NetScans) in LogicMonitor (LM) monitoring. 

**Returns:** Array of netscans with: id, name, description, scan method (nmap/script/ICMP/SNMP), schedule, target networks (IP ranges/subnets), collector, last run time, resource/device discovered. 

**What are netscans:** Automated network discovery that finds resource/device on your network and adds them to monitoring. Instead of manually adding resource/device one-by-one, netscan automatically discovers and onboards resource/device based on IP ranges or subnets. 

**When to use:**
- Audit existing discovery configurations
- Check which networks are being scanned
- Review netscan schedules
- Troubleshoot why resource/device not auto-discovered
- Find netscan IDs for modifications


**How netscans work:** Scheduled job → Scan network range (e.g., 192.168.1.0/24) → Find live resource/device → Check if already monitored → If new, add to LogicMonitor → Apply resource/device properties and datasources → Begin monitoring 

**NetScan methods:** 
- **nmap:** Network mapper scan (comprehensive, detects OS, ports, services) 
- **ICMP Ping:** Simple ping sweep (fastest, basic reachability) 
- **SNMP Walk:** Query SNMP-enabled resource/device (network gear, servers with SNMP) 
- **Script:** Custom discovery logic (cloud APIs, CMDBs, etc.) 
- **AWS/Azure/GCP:** Cloud auto-discovery via APIs 

**Common use cases:** 
- **Data center discovery:** Scan 10.0.0.0/16 network, auto-add all servers 
- **Cloud auto-discovery:** Scan AWS account, add all EC2 instances daily 
- **Branch office monitoring:** Scan remote office subnets, discover network resource/device 
- **Dynamic infrastructure:** Auto-discover containers, VMs as they spin up 

**Example NetScan configurations:** 
- "Production Servers" - Scan 192.168.1.0/24 every 6 hours via nmap 
- "AWS EC2 Discovery" - Query AWS API every hour for new instances 
- "Network resources/Devices" - SNMP walk 10.0.0.0/8 daily for routers/switches 

**Workflow:** Use this tool to review netscans, then "get\_netscan" for detailed configuration including filters and resource/device properties. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_netscan" (configuration details), "create\_netscan" (set up auto-discovery), "run\_netscan" (trigger manual scan).
  - This module wraps the MCP tool 'list_netscans'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all network discovery scans (NetScans) in LogicMonitor (LM) monitoring. 

**Returns:** Array of netscans with: id, name, description, scan method (nmap/script/ICMP/SNMP), schedule, target networks (IP ranges/subnets), collector, last run time, resource/device discovered. 

**What are netscans:** Automated network discovery that finds resource/device on your network and adds them to monitoring. Instead of manually adding resource/device one-by-one, netscan automatically discovers and onboards resource/device based on IP ranges or subnets. 

**When to use:**
- Audit existing discovery configurations
- Check which networks are being scanned
- Review netscan schedules
- Troubleshoot why resource/device not auto-discovered
- Find netscan IDs for modifications


**How netscans work:** Scheduled job → Scan network range (e.g., 192.168.1.0/24) → Find live resource/device → Check if already monitored → If new, add to LogicMonitor → Apply resource/device properties and datasources → Begin monitoring 

**NetScan methods:** 
- **nmap:** Network mapper scan (comprehensive, detects OS, ports, services) 
- **ICMP Ping:** Simple ping sweep (fastest, basic reachability) 
- **SNMP Walk:** Query SNMP-enabled resource/device (network gear, servers with SNMP) 
- **Script:** Custom discovery logic (cloud APIs, CMDBs, etc.) 
- **AWS/Azure/GCP:** Cloud auto-discovery via APIs 

**Common use cases:** 
- **Data center discovery:** Scan 10.0.0.0/16 network, auto-add all servers 
- **Cloud auto-discovery:** Scan AWS account, add all EC2 instances daily 
- **Branch office monitoring:** Scan remote office subnets, discover network resource/device 
- **Dynamic infrastructure:** Auto-discover containers, VMs as they spin up 

**Example NetScan configurations:** 
- "Production Servers" - Scan 192.168.1.0/24 every 6 hours via nmap 
- "AWS EC2 Discovery" - Query AWS API every hour for new instances 
- "Network resources/Devices" - SNMP walk 10.0.0.0/8 daily for routers/switches 

**Workflow:** Use this tool to review netscans, then "get\_netscan" for detailed configuration including filters and resource/device properties. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_netscan" (configuration details), "create\_netscan" (set up auto-discovery), "run\_netscan" (trigger manual scan).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all network discovery scans (NetScans) in LogicMonitor (LM) monitoring. 

**Returns:** Array of netscans with: id, name, description, scan method (nmap/script/ICMP/SNMP), schedule, target networks (IP ranges/subnets), collector, last run time, resource/device discovered. 

**What are netscans:** Automated network discovery that finds resource/device on your network and adds them to monitoring. Instead of manually adding resource/device one-by-one, netscan automatically discovers and onboards resource/device based on IP ranges or subnets. 

**When to use:**
- Audit existing discovery configurations
- Check which networks are being scanned
- Review netscan schedules
- Troubleshoot why resource/device not auto-discovered
- Find netscan IDs for modifications


**How netscans work:** Scheduled job → Scan network range (e.g., 192.168.1.0/24) → Find live resource/device → Check if already monitored → If new, add to LogicMonitor → Apply resource/device properties and datasources → Begin monitoring 

**NetScan methods:** 
- **nmap:** Network mapper scan (comprehensive, detects OS, ports, services) 
- **ICMP Ping:** Simple ping sweep (fastest, basic reachability) 
- **SNMP Walk:** Query SNMP-enabled resource/device (network gear, servers with SNMP) 
- **Script:** Custom discovery logic (cloud APIs, CMDBs, etc.) 
- **AWS/Azure/GCP:** Cloud auto-discovery via APIs 

**Common use cases:** 
- **Data center discovery:** Scan 10.0.0.0/16 network, auto-add all servers 
- **Cloud auto-discovery:** Scan AWS account, add all EC2 instances daily 
- **Branch office monitoring:** Scan remote office subnets, discover network resource/device 
- **Dynamic infrastructure:** Auto-discover containers, VMs as they spin up 

**Example NetScan configurations:** 
- "Production Servers" - Scan 192.168.1.0/24 every 6 hours via nmap 
- "AWS EC2 Discovery" - Query AWS API every hour for new instances 
- "Network resources/Devices" - SNMP walk 10.0.0.0/8 daily for routers/switches 

**Workflow:** Use this tool to review netscans, then "get\_netscan" for detailed configuration including filters and resource/device properties. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_netscan" (configuration details), "create\_netscan" (set up auto-discovery), "run\_netscan" (trigger manual scan).
      leogallego.logicmonitor_mcp.list_netscans:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_netscans"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
