#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_resource_properties
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_resource_properties
short_description: List all custom properties (system and user-defined) for a specific resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Array of properties with: name, value, source (device-level vs inherited from group), type (system vs custom). 

**When to use:** 
- Review resource/device configuration
- Check credentials/authentication settings
- See inherited vs device-specific properties
- Troubleshoot datasource applies logic
- Audit resource/device metadata

**Property types:** 

**System properties (auto-populated by LogicMonitor):** 
- system.hostname: Device hostname
- system.devicetype: Device category (server, network, cloud)
- system.ips: IP addresses
- system.categories: Auto-detected technologies (e.g., "AWS/EC2")

**Custom properties (user-defined):** 
- Credentials: ssh.user, snmp.community, wmi.user
- Tags: env (prod/staging), owner (team name), location
- Integration IDs: servicenow.ci_id, jira.project
- Business metadata: cost.center, sla.tier, backup.policy

**Property inheritance:** Properties can be set at: Device level (highest priority) → Group level → Parent group (inherited). 

**Datasource appliesTo logic uses properties:** Many datasources check properties to decide if they should monitor device. Example: AWS\_EC2 datasource checks if resource/device has "aws.resourcetype=ec2" property. 

**Workflow:** Use "list\_resources" to find deviceId, then use this tool to see all properties including inherited ones. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_property" (modify), "get\_resource" (see summary), "list\_datasources" (see how properties affect monitoring).
description:
  - List all custom properties (system and user-defined) for a specific resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Array of properties with: name, value, source (device-level vs inherited from group), type (system vs custom). 

**When to use:** 
- Review resource/device configuration
- Check credentials/authentication settings
- See inherited vs device-specific properties
- Troubleshoot datasource applies logic
- Audit resource/device metadata

**Property types:** 

**System properties (auto-populated by LogicMonitor):** 
- system.hostname: Device hostname
- system.devicetype: Device category (server, network, cloud)
- system.ips: IP addresses
- system.categories: Auto-detected technologies (e.g., "AWS/EC2")

**Custom properties (user-defined):** 
- Credentials: ssh.user, snmp.community, wmi.user
- Tags: env (prod/staging), owner (team name), location
- Integration IDs: servicenow.ci_id, jira.project
- Business metadata: cost.center, sla.tier, backup.policy

**Property inheritance:** Properties can be set at: Device level (highest priority) → Group level → Parent group (inherited). 

**Datasource appliesTo logic uses properties:** Many datasources check properties to decide if they should monitor device. Example: AWS\_EC2 datasource checks if resource/device has "aws.resourcetype=ec2" property. 

**Workflow:** Use "list\_resources" to find deviceId, then use this tool to see all properties including inherited ones. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_property" (modify), "get\_resource" (see summary), "list\_datasources" (see how properties affect monitoring).
  - This module wraps the MCP tool 'list_resource_properties'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  deviceId:
    description:
      - The resource/device ID
    type: float
    required: true
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all custom properties (system and user-defined) for a specific resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Array of properties with: name, value, source (device-level vs inherited from group), type (system vs custom). 

**When to use:** 
- Review resource/device configuration
- Check credentials/authentication settings
- See inherited vs device-specific properties
- Troubleshoot datasource applies logic
- Audit resource/device metadata

**Property types:** 

**System properties (auto-populated by LogicMonitor):** 
- system.hostname: Device hostname
- system.devicetype: Device category (server, network, cloud)
- system.ips: IP addresses
- system.categories: Auto-detected technologies (e.g., "AWS/EC2")

**Custom properties (user-defined):** 
- Credentials: ssh.user, snmp.community, wmi.user
- Tags: env (prod/staging), owner (team name), location
- Integration IDs: servicenow.ci_id, jira.project
- Business metadata: cost.center, sla.tier, backup.policy

**Property inheritance:** Properties can be set at: Device level (highest priority) → Group level → Parent group (inherited). 

**Datasource appliesTo logic uses properties:** Many datasources check properties to decide if they should monitor device. Example: AWS\_EC2 datasource checks if resource/device has "aws.resourcetype=ec2" property. 

**Workflow:** Use "list\_resources" to find deviceId, then use this tool to see all properties including inherited ones. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_property" (modify), "get\_resource" (see summary), "list\_datasources" (see how properties affect monitoring).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all custom properties (system and user-defined) for a specific resource/device in LogicMonitor (LM) monitoring. 

**Returns:** Array of properties with: name, value, source (device-level vs inherited from group), type (system vs custom). 

**When to use:** 
- Review resource/device configuration
- Check credentials/authentication settings
- See inherited vs device-specific properties
- Troubleshoot datasource applies logic
- Audit resource/device metadata

**Property types:** 

**System properties (auto-populated by LogicMonitor):** 
- system.hostname: Device hostname
- system.devicetype: Device category (server, network, cloud)
- system.ips: IP addresses
- system.categories: Auto-detected technologies (e.g., "AWS/EC2")

**Custom properties (user-defined):** 
- Credentials: ssh.user, snmp.community, wmi.user
- Tags: env (prod/staging), owner (team name), location
- Integration IDs: servicenow.ci_id, jira.project
- Business metadata: cost.center, sla.tier, backup.policy

**Property inheritance:** Properties can be set at: Device level (highest priority) → Group level → Parent group (inherited). 

**Datasource appliesTo logic uses properties:** Many datasources check properties to decide if they should monitor device. Example: AWS\_EC2 datasource checks if resource/device has "aws.resourcetype=ec2" property. 

**Workflow:** Use "list\_resources" to find deviceId, then use this tool to see all properties including inherited ones. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "update\_device\_property" (modify), "get\_resource" (see summary), "list\_datasources" (see how properties affect monitoring).
      leogallego.logicmonitor_mcp.list_resource_properties:
        deviceId: "CHANGEME"
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_resource_properties"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            deviceId=dict(
                type="float",
                required=True,
            ),
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
