#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_recipient_groups
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_recipient_groups
short_description: List all recipient groups in LogicMonitor (LM) monitoring. 

**Returns:** Array of recipient groups with: id, name, description, member count, recipients list. 

**What are recipient groups:** Collections of recipients treated as a single notification target. Simplify escalation chains by notifying entire teams at once. Example: "Database Team" group contains 5 team members - notify group = notify all 5. 

**When to use:**
- Find group IDs for escalation chains
- Audit team notification lists
- Review group membership before changes
- Simplify notification management


**Benefits over individual recipients:** 
- **Easier management:** Update team once, applies to all escalation chains using that group 
- **Team notifications:** Notify entire team simultaneously 
- **Organized:** Group by function (DB team, Network team, On-call rotation) 

**Common recipient groups:** 
- "On-Call Engineers" - Current on-call rotation members 
- "Database Team" - All database administrators 
- "Network Operations" - NOC team members 
- "Management" - For escalation to leadership 

**Use cases:** 
- "Notify entire team for critical alerts" → Use group instead of 5 individual recipients 
- "Rotate on-call" → Update group members without touching escalation chains 
- "Add new team member" → Add to group, automatically included in alerts 

**Workflow:** Use this tool to find groups, then use in escalation chains to notify multiple people at once. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_recipient\_group" (details), "list\_recipients" (individual members), "list\_escalation\_chains" (see usage).
description:
  - List all recipient groups in LogicMonitor (LM) monitoring. 

**Returns:** Array of recipient groups with: id, name, description, member count, recipients list. 

**What are recipient groups:** Collections of recipients treated as a single notification target. Simplify escalation chains by notifying entire teams at once. Example: "Database Team" group contains 5 team members - notify group = notify all 5. 

**When to use:**
- Find group IDs for escalation chains
- Audit team notification lists
- Review group membership before changes
- Simplify notification management


**Benefits over individual recipients:** 
- **Easier management:** Update team once, applies to all escalation chains using that group 
- **Team notifications:** Notify entire team simultaneously 
- **Organized:** Group by function (DB team, Network team, On-call rotation) 

**Common recipient groups:** 
- "On-Call Engineers" - Current on-call rotation members 
- "Database Team" - All database administrators 
- "Network Operations" - NOC team members 
- "Management" - For escalation to leadership 

**Use cases:** 
- "Notify entire team for critical alerts" → Use group instead of 5 individual recipients 
- "Rotate on-call" → Update group members without touching escalation chains 
- "Add new team member" → Add to group, automatically included in alerts 

**Workflow:** Use this tool to find groups, then use in escalation chains to notify multiple people at once. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_recipient\_group" (details), "list\_recipients" (individual members), "list\_escalation\_chains" (see usage).
  - This module wraps the MCP tool 'list_recipient_groups'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all recipient groups in LogicMonitor (LM) monitoring. 

**Returns:** Array of recipient groups with: id, name, description, member count, recipients list. 

**What are recipient groups:** Collections of recipients treated as a single notification target. Simplify escalation chains by notifying entire teams at once. Example: "Database Team" group contains 5 team members - notify group = notify all 5. 

**When to use:**
- Find group IDs for escalation chains
- Audit team notification lists
- Review group membership before changes
- Simplify notification management


**Benefits over individual recipients:** 
- **Easier management:** Update team once, applies to all escalation chains using that group 
- **Team notifications:** Notify entire team simultaneously 
- **Organized:** Group by function (DB team, Network team, On-call rotation) 

**Common recipient groups:** 
- "On-Call Engineers" - Current on-call rotation members 
- "Database Team" - All database administrators 
- "Network Operations" - NOC team members 
- "Management" - For escalation to leadership 

**Use cases:** 
- "Notify entire team for critical alerts" → Use group instead of 5 individual recipients 
- "Rotate on-call" → Update group members without touching escalation chains 
- "Add new team member" → Add to group, automatically included in alerts 

**Workflow:** Use this tool to find groups, then use in escalation chains to notify multiple people at once. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_recipient\_group" (details), "list\_recipients" (individual members), "list\_escalation\_chains" (see usage).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all recipient groups in LogicMonitor (LM) monitoring. 

**Returns:** Array of recipient groups with: id, name, description, member count, recipients list. 

**What are recipient groups:** Collections of recipients treated as a single notification target. Simplify escalation chains by notifying entire teams at once. Example: "Database Team" group contains 5 team members - notify group = notify all 5. 

**When to use:**
- Find group IDs for escalation chains
- Audit team notification lists
- Review group membership before changes
- Simplify notification management


**Benefits over individual recipients:** 
- **Easier management:** Update team once, applies to all escalation chains using that group 
- **Team notifications:** Notify entire team simultaneously 
- **Organized:** Group by function (DB team, Network team, On-call rotation) 

**Common recipient groups:** 
- "On-Call Engineers" - Current on-call rotation members 
- "Database Team" - All database administrators 
- "Network Operations" - NOC team members 
- "Management" - For escalation to leadership 

**Use cases:** 
- "Notify entire team for critical alerts" → Use group instead of 5 individual recipients 
- "Rotate on-call" → Update group members without touching escalation chains 
- "Add new team member" → Add to group, automatically included in alerts 

**Workflow:** Use this tool to find groups, then use in escalation chains to notify multiple people at once. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_recipient\_group" (details), "list\_recipients" (individual members), "list\_escalation\_chains" (see usage).
      leogallego.logicmonitor_mcp.list_recipient_groups:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_recipient_groups"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
