#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_opsnotes
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_opsnotes
short_description: List all operational notes (OpsNotes) in LogicMonitor (LM) monitoring. 

**Returns:** Array of OpsNotes with: id, note text, timestamp (epoch), who created it, tags, scope (applies to which resources/devices/groups), related SDTs. 

**What are OpsNotes:** Timestamped operational annotations displayed on graphs and dashboards. Document changes, deployments, maintenance, incidents - anything that might affect metrics. Appear as vertical lines on metric graphs at the time they occurred. 

**When to use:**
- Correlate metric changes with operational events
- Document deployments/changes
- Create timeline of incidents and responses
- Track maintenance activities
- Generate operational reports


**Use cases and examples:** 

**Deployments:** 
- "Deployed v2.5.0 to production" (explains CPU spike at deploy time) 
- "Database schema migration" (explains slow queries during migration) 

**Incidents:** 
- "Customer reported slow load times - investigating" 
- "Found memory leak, restarting services" 
- "Incident resolved - bad cache configuration" 

**Maintenance:** 
- "Scaled from 10 to 15 instances" 
- "Updated SSL certificates" 
- "Cleared old logs, freed 500GB disk" 

**Benefits:** 
- **Troubleshooting:** "Latency increased at 2pm" → Check OpsNotes: "Deploy happened at 2pm" 
- **Correlation:** Understand cause of metric anomalies 
- **Documentation:** Automatic operational timeline 
- **Communication:** Share what happened with team 

**Common filter patterns:** 
- By time: filter:"happenedOn>1730851200" (recent notes) 
- By tags: filter:"tags~*deployment*" 
- By device: filter:"monitorObjectName~*prod-web*" 

**Displayed on:** Graphs, dashboards, resource/device pages - visible wherever metrics are shown. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_opsnote" (details), "create\_opsnote" (add new), "create\_device\_sdt" (maintenance windows).
description:
  - List all operational notes (OpsNotes) in LogicMonitor (LM) monitoring. 

**Returns:** Array of OpsNotes with: id, note text, timestamp (epoch), who created it, tags, scope (applies to which resources/devices/groups), related SDTs. 

**What are OpsNotes:** Timestamped operational annotations displayed on graphs and dashboards. Document changes, deployments, maintenance, incidents - anything that might affect metrics. Appear as vertical lines on metric graphs at the time they occurred. 

**When to use:**
- Correlate metric changes with operational events
- Document deployments/changes
- Create timeline of incidents and responses
- Track maintenance activities
- Generate operational reports


**Use cases and examples:** 

**Deployments:** 
- "Deployed v2.5.0 to production" (explains CPU spike at deploy time) 
- "Database schema migration" (explains slow queries during migration) 

**Incidents:** 
- "Customer reported slow load times - investigating" 
- "Found memory leak, restarting services" 
- "Incident resolved - bad cache configuration" 

**Maintenance:** 
- "Scaled from 10 to 15 instances" 
- "Updated SSL certificates" 
- "Cleared old logs, freed 500GB disk" 

**Benefits:** 
- **Troubleshooting:** "Latency increased at 2pm" → Check OpsNotes: "Deploy happened at 2pm" 
- **Correlation:** Understand cause of metric anomalies 
- **Documentation:** Automatic operational timeline 
- **Communication:** Share what happened with team 

**Common filter patterns:** 
- By time: filter:"happenedOn>1730851200" (recent notes) 
- By tags: filter:"tags~*deployment*" 
- By device: filter:"monitorObjectName~*prod-web*" 

**Displayed on:** Graphs, dashboards, resource/device pages - visible wherever metrics are shown. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_opsnote" (details), "create\_opsnote" (add new), "create\_device\_sdt" (maintenance windows).
  - This module wraps the MCP tool 'list_opsnotes'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all operational notes (OpsNotes) in LogicMonitor (LM) monitoring. 

**Returns:** Array of OpsNotes with: id, note text, timestamp (epoch), who created it, tags, scope (applies to which resources/devices/groups), related SDTs. 

**What are OpsNotes:** Timestamped operational annotations displayed on graphs and dashboards. Document changes, deployments, maintenance, incidents - anything that might affect metrics. Appear as vertical lines on metric graphs at the time they occurred. 

**When to use:**
- Correlate metric changes with operational events
- Document deployments/changes
- Create timeline of incidents and responses
- Track maintenance activities
- Generate operational reports


**Use cases and examples:** 

**Deployments:** 
- "Deployed v2.5.0 to production" (explains CPU spike at deploy time) 
- "Database schema migration" (explains slow queries during migration) 

**Incidents:** 
- "Customer reported slow load times - investigating" 
- "Found memory leak, restarting services" 
- "Incident resolved - bad cache configuration" 

**Maintenance:** 
- "Scaled from 10 to 15 instances" 
- "Updated SSL certificates" 
- "Cleared old logs, freed 500GB disk" 

**Benefits:** 
- **Troubleshooting:** "Latency increased at 2pm" → Check OpsNotes: "Deploy happened at 2pm" 
- **Correlation:** Understand cause of metric anomalies 
- **Documentation:** Automatic operational timeline 
- **Communication:** Share what happened with team 

**Common filter patterns:** 
- By time: filter:"happenedOn>1730851200" (recent notes) 
- By tags: filter:"tags~*deployment*" 
- By device: filter:"monitorObjectName~*prod-web*" 

**Displayed on:** Graphs, dashboards, resource/device pages - visible wherever metrics are shown. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_opsnote" (details), "create\_opsnote" (add new), "create\_device\_sdt" (maintenance windows).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all operational notes (OpsNotes) in LogicMonitor (LM) monitoring. 

**Returns:** Array of OpsNotes with: id, note text, timestamp (epoch), who created it, tags, scope (applies to which resources/devices/groups), related SDTs. 

**What are OpsNotes:** Timestamped operational annotations displayed on graphs and dashboards. Document changes, deployments, maintenance, incidents - anything that might affect metrics. Appear as vertical lines on metric graphs at the time they occurred. 

**When to use:**
- Correlate metric changes with operational events
- Document deployments/changes
- Create timeline of incidents and responses
- Track maintenance activities
- Generate operational reports


**Use cases and examples:** 

**Deployments:** 
- "Deployed v2.5.0 to production" (explains CPU spike at deploy time) 
- "Database schema migration" (explains slow queries during migration) 

**Incidents:** 
- "Customer reported slow load times - investigating" 
- "Found memory leak, restarting services" 
- "Incident resolved - bad cache configuration" 

**Maintenance:** 
- "Scaled from 10 to 15 instances" 
- "Updated SSL certificates" 
- "Cleared old logs, freed 500GB disk" 

**Benefits:** 
- **Troubleshooting:** "Latency increased at 2pm" → Check OpsNotes: "Deploy happened at 2pm" 
- **Correlation:** Understand cause of metric anomalies 
- **Documentation:** Automatic operational timeline 
- **Communication:** Share what happened with team 

**Common filter patterns:** 
- By time: filter:"happenedOn>1730851200" (recent notes) 
- By tags: filter:"tags~*deployment*" 
- By device: filter:"monitorObjectName~*prod-web*" 

**Displayed on:** Graphs, dashboards, resource/device pages - visible wherever metrics are shown. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_opsnote" (details), "create\_opsnote" (add new), "create\_device\_sdt" (maintenance windows).
      leogallego.logicmonitor_mcp.list_opsnotes:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_opsnotes"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
