#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_resources
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_resources
short_description: List all monitored resources/devices in LogicMonitor (LM) monitoring. 

**Returns:** Array of resource/device with: id, displayName, name (IP/hostname), hostStatus (dead/alive/unknown), preferredCollectorId, deviceType, custom properties, group memberships. 

**When to use:** 
- Get inventory of all monitored resources/devices
- Find specific resource/device by name/IP/property
- Check resource/device health status
- Get resource/device IDs for other operations

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"production", query:"web-server") - automatically searches displayName, description, and name fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"hostStatus:alive,displayName~\*web\*") for precise control

**Common filter patterns:** 
- By name: filter:"displayName\~\*prod\*" (wildcard search) 
- By status: filter:"hostStatus:alive" or filter:"hostStatus:dead" 
- By type: filter:"systemProperties.name:system.devicetype,value:server" 
- By custom property: filter:"customProperties.name:company.team,customProperties.value:teamA" 
- By collector: filter:"preferredCollectorId:123" 
- Multiple conditions: filter:"hostStatus:alive,displayName\~\*web\*" (comma = AND) 

**Query vs Filter:** 
- query: Simplified search across displayName, description, name (OR logic). Use for quick lookups: query:"prod-web-01"
- filter: Precise LM filter syntax with any field. Use for complex conditions: filter:"hostStatus:alive,displayName~\*prod\*"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Performance tips:** Use autoPaginate:false for large environments (>1000 resources/devices) and paginate manually to avoid timeouts. 

**Related tools:** "get\_resource" (details), "generate\_resource\_link" (get UI link).
description:
  - List all monitored resources/devices in LogicMonitor (LM) monitoring. 

**Returns:** Array of resource/device with: id, displayName, name (IP/hostname), hostStatus (dead/alive/unknown), preferredCollectorId, deviceType, custom properties, group memberships. 

**When to use:** 
- Get inventory of all monitored resources/devices
- Find specific resource/device by name/IP/property
- Check resource/device health status
- Get resource/device IDs for other operations

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"production", query:"web-server") - automatically searches displayName, description, and name fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"hostStatus:alive,displayName~\*web\*") for precise control

**Common filter patterns:** 
- By name: filter:"displayName\~\*prod\*" (wildcard search) 
- By status: filter:"hostStatus:alive" or filter:"hostStatus:dead" 
- By type: filter:"systemProperties.name:system.devicetype,value:server" 
- By custom property: filter:"customProperties.name:company.team,customProperties.value:teamA" 
- By collector: filter:"preferredCollectorId:123" 
- Multiple conditions: filter:"hostStatus:alive,displayName\~\*web\*" (comma = AND) 

**Query vs Filter:** 
- query: Simplified search across displayName, description, name (OR logic). Use for quick lookups: query:"prod-web-01"
- filter: Precise LM filter syntax with any field. Use for complex conditions: filter:"hostStatus:alive,displayName~\*prod\*"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Performance tips:** Use autoPaginate:false for large environments (>1000 resources/devices) and paginate manually to avoid timeouts. 

**Related tools:** "get\_resource" (details), "generate\_resource\_link" (get UI link).
  - This module wraps the MCP tool 'list_resources'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  query:
    description:
      - Simple search query. Free text (e.g., "production", "web-server", "192.168.1.100") automatically searches across displayName, description, and name fields. Can also use filter syntax (e.g., "hostStatus:alive") which gets formatted automatically.
    type: str
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all monitored resources/devices in LogicMonitor (LM) monitoring. 

**Returns:** Array of resource/device with: id, displayName, name (IP/hostname), hostStatus (dead/alive/unknown), preferredCollectorId, deviceType, custom properties, group memberships. 

**When to use:** 
- Get inventory of all monitored resources/devices
- Find specific resource/device by name/IP/property
- Check resource/device health status
- Get resource/device IDs for other operations

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"production", query:"web-server") - automatically searches displayName, description, and name fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"hostStatus:alive,displayName~\*web\*") for precise control

**Common filter patterns:** 
- By name: filter:"displayName\~\*prod\*" (wildcard search) 
- By status: filter:"hostStatus:alive" or filter:"hostStatus:dead" 
- By type: filter:"systemProperties.name:system.devicetype,value:server" 
- By custom property: filter:"customProperties.name:company.team,customProperties.value:teamA" 
- By collector: filter:"preferredCollectorId:123" 
- Multiple conditions: filter:"hostStatus:alive,displayName\~\*web\*" (comma = AND) 

**Query vs Filter:** 
- query: Simplified search across displayName, description, name (OR logic). Use for quick lookups: query:"prod-web-01"
- filter: Precise LM filter syntax with any field. Use for complex conditions: filter:"hostStatus:alive,displayName~\*prod\*"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Performance tips:** Use autoPaginate:false for large environments (>1000 resources/devices) and paginate manually to avoid timeouts. 

**Related tools:** "get\_resource" (details), "generate\_resource\_link" (get UI link).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all monitored resources/devices in LogicMonitor (LM) monitoring. 

**Returns:** Array of resource/device with: id, displayName, name (IP/hostname), hostStatus (dead/alive/unknown), preferredCollectorId, deviceType, custom properties, group memberships. 

**When to use:** 
- Get inventory of all monitored resources/devices
- Find specific resource/device by name/IP/property
- Check resource/device health status
- Get resource/device IDs for other operations

**Two search modes:** 
- **Simple search:** Use query parameter with free text (e.g., query:"production", query:"web-server") - automatically searches displayName, description, and name fields
- **Advanced filtering:** Use filter parameter with LM filter syntax (e.g., filter:"hostStatus:alive,displayName~\*web\*") for precise control

**Common filter patterns:** 
- By name: filter:"displayName\~\*prod\*" (wildcard search) 
- By status: filter:"hostStatus:alive" or filter:"hostStatus:dead" 
- By type: filter:"systemProperties.name:system.devicetype,value:server" 
- By custom property: filter:"customProperties.name:company.team,customProperties.value:teamA" 
- By collector: filter:"preferredCollectorId:123" 
- Multiple conditions: filter:"hostStatus:alive,displayName\~\*web\*" (comma = AND) 

**Query vs Filter:** 
- query: Simplified search across displayName, description, name (OR logic). Use for quick lookups: query:"prod-web-01"
- filter: Precise LM filter syntax with any field. Use for complex conditions: filter:"hostStatus:alive,displayName~\*prod\*"
- If both provided, query is converted to filter and combined with provided filter using AND logic

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Performance tips:** Use autoPaginate:false for large environments (>1000 resources/devices) and paginate manually to avoid timeouts. 

**Related tools:** "get\_resource" (details), "generate\_resource\_link" (get UI link).
      leogallego.logicmonitor_mcp.list_resources:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_resources"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            query=dict(
                type="str",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
