#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by AnsibleClaw from MCP tool: list_reports
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type


DOCUMENTATION = r"""
---
module: list_reports
short_description: List all reports (scheduled and on-demand) in LogicMonitor (LM) monitoring. 

**Returns:** Array of reports with: id, name, type (alert/availability/capacity/performance), description, schedule, recipients, format (PDF/HTML/CSV), last run time. 

**What are reports:** Scheduled or on-demand documents summarizing monitoring data. Generate PDFs, HTML, or CSV files with metrics, alerts, availability statistics, capacity planning data. Automatically email to stakeholders. 

**When to use:** 
- Find existing reports before creating duplicates
- Review report schedules
- Check who receives reports
- Audit reporting configuration

**Report types:** 
- **Alert Reports:** Summary of alerts over time period (count by severity, MTTR, top alerting resources/devices)
- **Availability Reports:** Uptime statistics, SLA compliance, outage summaries
- **Capacity Planning:** Disk growth trends, CPU/memory usage over time, forecasting
- **Performance Reports:** Metric trends, top consumers, performance baselines
- **Custom Reports:** User-defined queries and visualizations

**Common use cases:** 
- **Executive summaries:** Monthly availability report to leadership
- **SLA reporting:** Prove 99.9% uptime to customers
- **Capacity planning:** Forecast when to add storage/servers
- **Compliance:** Document monitoring coverage and alert response
- **Billing:** Usage reports for chargebacks

**Report schedules:** 
- Daily: 8am delivery for NOC shift handoff
- Weekly: Monday morning management briefing
- Monthly: End-of-month SLA reports
- Quarterly: Capacity planning reviews
- On-demand: Generate for specific incidents/audits

**Workflow:** Use this tool to find reports, then "get\_report" for details, or "generate\_report" to run on-demand. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_report" (details), "list\_report\_groups" (organization), "generate\_report" (run now).
description:
  - List all reports (scheduled and on-demand) in LogicMonitor (LM) monitoring. 

**Returns:** Array of reports with: id, name, type (alert/availability/capacity/performance), description, schedule, recipients, format (PDF/HTML/CSV), last run time. 

**What are reports:** Scheduled or on-demand documents summarizing monitoring data. Generate PDFs, HTML, or CSV files with metrics, alerts, availability statistics, capacity planning data. Automatically email to stakeholders. 

**When to use:** 
- Find existing reports before creating duplicates
- Review report schedules
- Check who receives reports
- Audit reporting configuration

**Report types:** 
- **Alert Reports:** Summary of alerts over time period (count by severity, MTTR, top alerting resources/devices)
- **Availability Reports:** Uptime statistics, SLA compliance, outage summaries
- **Capacity Planning:** Disk growth trends, CPU/memory usage over time, forecasting
- **Performance Reports:** Metric trends, top consumers, performance baselines
- **Custom Reports:** User-defined queries and visualizations

**Common use cases:** 
- **Executive summaries:** Monthly availability report to leadership
- **SLA reporting:** Prove 99.9% uptime to customers
- **Capacity planning:** Forecast when to add storage/servers
- **Compliance:** Document monitoring coverage and alert response
- **Billing:** Usage reports for chargebacks

**Report schedules:** 
- Daily: 8am delivery for NOC shift handoff
- Weekly: Monday morning management briefing
- Monthly: End-of-month SLA reports
- Quarterly: Capacity planning reviews
- On-demand: Generate for specific incidents/audits

**Workflow:** Use this tool to find reports, then "get\_report" for details, or "generate\_report" to run on-demand. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_report" (details), "list\_report\_groups" (organization), "generate\_report" (run now).
  - This module wraps the MCP tool 'list_reports'.
  - Requires the C(ansible.mcp) collection and an MCP server connection.
version_added: "1.0.0"
author:
  - Auto-generated by AnsibleClaw
options:
  autoPaginate:
    description:
      - Automatically fetch all pages (default: false). When true, fetches all results across multiple pages. When false, returns only the requested page. Use false for large result sets to avoid long response times.
    type: bool
    required: false
  fields:
    description:
      - Comma-separated list of fields to include in response. Examples: "id,displayName,hostStatus" or use "*" for all fields. Omit this parameter to receive a curated set of commonly used fields.
    type: str
    required: false
  filter:
    description:
      - Filter expression using LogicMonitor query syntax. Examples: name:*prod*, displayName~*server*, id>100, hostStatus:normal. Available operators: : (equals), ~ (includes), !: (not equals), !~ (not includes), >: (greater than or equals), <: (less than or equals), > (greater than), < (less than). Multiple conditions: Use comma (,) for AND, use || for OR. Do NOT use &&.
    type: str
    required: false
  offset:
    description:
      - Starting offset for pagination (default: 0). Use this to skip a specific number of results.
    type: float
    required: false
  size:
    description:
      - Number of results per page (default: 50, max: 1000).
    type: float
    required: false
seealso:
  - module: ansible.mcp.run_tool
    description: Generic MCP tool runner this module delegates to.
requirements:
  - ansible.mcp collection installed
  - MCP server accessible via ansible.mcp.mcp connection
"""

EXAMPLES = r"""
---
- name: List all reports (scheduled and on-demand) in LogicMonitor (LM) monitoring. 

**Returns:** Array of reports with: id, name, type (alert/availability/capacity/performance), description, schedule, recipients, format (PDF/HTML/CSV), last run time. 

**What are reports:** Scheduled or on-demand documents summarizing monitoring data. Generate PDFs, HTML, or CSV files with metrics, alerts, availability statistics, capacity planning data. Automatically email to stakeholders. 

**When to use:** 
- Find existing reports before creating duplicates
- Review report schedules
- Check who receives reports
- Audit reporting configuration

**Report types:** 
- **Alert Reports:** Summary of alerts over time period (count by severity, MTTR, top alerting resources/devices)
- **Availability Reports:** Uptime statistics, SLA compliance, outage summaries
- **Capacity Planning:** Disk growth trends, CPU/memory usage over time, forecasting
- **Performance Reports:** Metric trends, top consumers, performance baselines
- **Custom Reports:** User-defined queries and visualizations

**Common use cases:** 
- **Executive summaries:** Monthly availability report to leadership
- **SLA reporting:** Prove 99.9% uptime to customers
- **Capacity planning:** Forecast when to add storage/servers
- **Compliance:** Document monitoring coverage and alert response
- **Billing:** Usage reports for chargebacks

**Report schedules:** 
- Daily: 8am delivery for NOC shift handoff
- Weekly: Monday morning management briefing
- Monthly: End-of-month SLA reports
- Quarterly: Capacity planning reviews
- On-demand: Generate for specific incidents/audits

**Workflow:** Use this tool to find reports, then "get\_report" for details, or "generate\_report" to run on-demand. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_report" (details), "list\_report\_groups" (organization), "generate\_report" (run now).
  hosts: mcp_servers
  connection: ansible.mcp.mcp
  gather_facts: false
  vars:
    ansible_mcp_server_name: "CHANGEME"
  tasks:
    - name: List all reports (scheduled and on-demand) in LogicMonitor (LM) monitoring. 

**Returns:** Array of reports with: id, name, type (alert/availability/capacity/performance), description, schedule, recipients, format (PDF/HTML/CSV), last run time. 

**What are reports:** Scheduled or on-demand documents summarizing monitoring data. Generate PDFs, HTML, or CSV files with metrics, alerts, availability statistics, capacity planning data. Automatically email to stakeholders. 

**When to use:** 
- Find existing reports before creating duplicates
- Review report schedules
- Check who receives reports
- Audit reporting configuration

**Report types:** 
- **Alert Reports:** Summary of alerts over time period (count by severity, MTTR, top alerting resources/devices)
- **Availability Reports:** Uptime statistics, SLA compliance, outage summaries
- **Capacity Planning:** Disk growth trends, CPU/memory usage over time, forecasting
- **Performance Reports:** Metric trends, top consumers, performance baselines
- **Custom Reports:** User-defined queries and visualizations

**Common use cases:** 
- **Executive summaries:** Monthly availability report to leadership
- **SLA reporting:** Prove 99.9% uptime to customers
- **Capacity planning:** Forecast when to add storage/servers
- **Compliance:** Document monitoring coverage and alert response
- **Billing:** Usage reports for chargebacks

**Report schedules:** 
- Daily: 8am delivery for NOC shift handoff
- Weekly: Monday morning management briefing
- Monthly: End-of-month SLA reports
- Quarterly: Capacity planning reviews
- On-demand: Generate for specific incidents/audits

**Workflow:** Use this tool to find reports, then "get\_report" for details, or "generate\_report" to run on-demand. 

**Important:** A negative "total" value in the response indicates incomplete results. Use pagination (size/offset parameters) or set autoPaginate: true to retrieve all items. 

**Related tools:** "get\_report" (details), "list\_report\_groups" (organization), "generate\_report" (run now).
      leogallego.logicmonitor_mcp.list_reports:
      register: result
"""

RETURN = r"""
---
content:
  description: List of content blocks returned by the MCP tool.
  type: list
  returned: always
  elements: dict
is_error:
  description: Whether the MCP tool reported an error.
  type: bool
  returned: always
structured_content:
  description: Optional structured result data from the MCP tool.
  type: dict
  returned: when available
tool_name:
  description: Name of the MCP tool that was called.
  type: str
  returned: always
tool_classification:
  description: Tool classification information (read_only, destructive).
  type: dict
  returned: always
"""


MCP_TOOL_NAME = "list_reports"


from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            autoPaginate=dict(
                type="bool",
            ),
            fields=dict(
                type="str",
            ),
            filter=dict(
                type="str",
            ),
            offset=dict(
                type="float",
            ),
            size=dict(
                type="float",
            ),
        ),
        supports_check_mode=True,
    )

    if module.check_mode:
        module.exit_json(changed=False, msg="Check mode: no MCP call made")

    tool_args = {k: v for k, v in module.params.items() if v is not None}

    module.exit_json(
        changed=False,
        _mcp_delegate=dict(
            name=MCP_TOOL_NAME,
            args=tool_args,
        ),
    )


if __name__ == "__main__":
    main()
