# _mcp_proxy.py - Shared action plugin for MCP-generated modules.
# Auto-generated by AnsibleClaw.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, annotations, division, print_function

__metaclass__ = type

from typing import TYPE_CHECKING

from ansible.plugins.action import ActionBase


if TYPE_CHECKING:
    from typing import Any, Dict, Optional


class ActionModule(ActionBase):
    """Proxy action plugin that delegates to ansible.mcp.run_tool.

    Each generated module declares a MCP_TOOL_NAME constant. This
    action plugin reads the module's argument_spec-validated parameters
    and forwards them to ansible.mcp.run_tool via the MCP connection.
    """

    def run(
        self,
        tmp: Optional[str] = None,
        task_vars: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        if task_vars is None:
            task_vars = {}

        result = super().run(tmp, task_vars)

        module_args = self._task.args.copy()

        module_name = self._task.action.split(".")[-1]
        module_fqcn = self._task.action

        try:
            module_ref = self._shared_loader_obj.module_loader.find_plugin(
                module_fqcn, collection_list=self._task.collections
            )
            if module_ref:
                import importlib.util
                spec = importlib.util.spec_from_file_location("_mod", module_ref)
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)
                tool_name = getattr(mod, "MCP_TOOL_NAME", module_name)
            else:
                tool_name = module_name
        except Exception:
            tool_name = module_name

        tool_args = {k: v for k, v in module_args.items() if v is not None}

        run_tool_args = {
            "name": tool_name,
            "args": tool_args,
        }

        result.update(
            self._execute_module(
                module_name="ansible.mcp.run_tool",
                module_args=run_tool_args,
                task_vars=task_vars,
                tmp=tmp,
            ),
        )

        return result
